//! Build-time generated embedded price table.
//!
//! This module includes the Rust source generated by `build.rs` from
//! `pricing/data/<version>.yaml`. The generated code provides:
//!
//! - `PRICE_TABLE_VERSION` — the version string of the embedded data.
//! - `EmbeddedPriceSchedule` — per-class pricing fields.
//! - `EmbeddedPriceEntry` — a `(provider, region, class)` keyed entry.
//! - `embedded_price_table()` — returns the full static table.
//! - `lookup_price(provider, region, class)` — point lookup.

include!(concat!(env!("OUT_DIR"), "/pricing_embedded.rs"));
