apiVersion: v1
kind: Service
metadata:
  name: {{ include "crab-s3-gateway.fullname" . }}
  labels:
    {{- include "crab-s3-gateway.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
    - name: s3
      port: {{ .Values.service.port }}
      targetPort: s3
      protocol: TCP
  selector:
    {{- include "crab-s3-gateway.selectorLabels" . | nindent 4 }}
