//! Local Git pack consolidation with complete object-graph verification.

use std::collections::BTreeSet;
use std::fs::File;
use std::io::{self, BufRead, BufReader, Read, Seek, Write};
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};
use std::time::Instant;

use crate::pack::{
    PackError, install_pack_file_from_path, verify_and_hash_pack_file, verify_pack_file_sha1,
};
use crate::pack_locator::{PackLocationIter, PackLocatorError, write_pack_reverse_index};
use sha1::{Digest, Sha1};

const DEFAULT_REPACK_INDEX_CONCURRENCY: usize = 8;
const MAX_VERIFY_PACKS_PER_COMMAND: usize = 512;

/// A downloaded canonical pack selected by a pinned repository manifest.
#[derive(Debug, Clone)]
pub struct RepackSource {
    /// Blake3 content identifier used by the canonical repository inventory.
    pub canonical_id: String,
    /// Local path containing the complete pack body.
    pub path: PathBuf,
    /// Size committed by the source manifest.
    pub size: u64,
    /// Object count committed by the source manifest.
    pub object_count: u64,
}

/// One authorized annotated tag considered for shallow fetch inclusion.
#[derive(Debug, Clone, Copy)]
pub struct ShallowFetchTag {
    /// Annotated tag object referenced by the visible tag ref.
    pub target: gix_hash::ObjectId,
    /// Final object referenced by the annotated tag chain.
    pub peeled: gix_hash::ObjectId,
}

/// A verified pack produced by geometric consolidation.
#[derive(Debug)]
pub struct GeometricRepackedPack {
    pack_path: PathBuf,
    index_path: PathBuf,
    reverse_index_path: PathBuf,
    /// Blake3 content identifier of the pack.
    pub pack_id: String,
    /// Raw Blake3 digest used by multipart integrity verification.
    pub pack_hash: [u8; 32],
    /// Pack size.
    pub pack_size: u64,
    /// Raw Blake3 digest of the Git index.
    pub index_hash: [u8; 32],
    /// Git index size.
    pub index_size: u64,
    /// Raw Blake3 digest of the reverse index.
    pub reverse_index_hash: [u8; 32],
    /// Git reverse-index size.
    pub reverse_index_size: u64,
    /// Number of objects in the pack.
    pub object_count: u64,
    /// Git-native SHA-1 checksum of the pack.
    pub git_sha1: String,
    /// Whether the pack body was newly generated by geometric repack.
    pub is_new: bool,
}

impl GeometricRepackedPack {
    /// Returns the verified pack path.
    #[must_use]
    pub fn pack_path(&self) -> &Path {
        &self.pack_path
    }

    /// Returns the verified Git index path.
    #[must_use]
    pub fn index_path(&self) -> &Path {
        &self.index_path
    }

    /// Returns the verified Git reverse-index path.
    #[must_use]
    pub fn reverse_index_path(&self) -> &Path {
        &self.reverse_index_path
    }
}

/// A verified geometric replacement pack set.
#[derive(Debug)]
pub struct GeometricRepackedRepository {
    _workspace: tempfile::TempDir,
    packs: Vec<GeometricRepackedPack>,
}

impl GeometricRepackedRepository {
    /// Returns all packs in the verified replacement inventory.
    #[must_use]
    pub fn packs(&self) -> &[GeometricRepackedPack] {
        &self.packs
    }
}

/// Errors raised while consolidating a complete Git object database.
#[derive(Debug, thiserror::Error)]
#[non_exhaustive]
pub enum RepackError {
    /// Filesystem work failed.
    #[error("{context}: {source}")]
    Io {
        context: String,
        #[source]
        source: io::Error,
    },
    /// A source pack failed Git pack validation.
    #[error(transparent)]
    Pack {
        #[from]
        source: PackError,
    },
    /// A generated or installed pack index failed locator validation.
    #[error(transparent)]
    Locator {
        #[from]
        source: PackLocatorError,
    },
    /// A source pack no longer matches its manifest commitment.
    #[error("source pack {pack_id} failed its manifest commitment: {reason}")]
    SourceIntegrity { pack_id: String, reason: String },
    /// Repacking an inventory without refs cannot prove repository reachability.
    #[error("cannot repack a repository without refs")]
    EmptyRefs,
    /// A Git subprocess rejected the source or replacement repository.
    #[error("{operation} failed with {status}")]
    Git {
        operation: &'static str,
        status: std::process::ExitStatus,
    },
    /// A selected-object pack contained an object outside the requested set.
    #[error("selected pack {pack_id} failed exact object-set validation: {reason}")]
    SelectedObjectSet { pack_id: String, reason: String },
}

#[derive(Clone, Copy)]
enum GeneratedPackValidation {
    Structural,
    Full,
}

/// Return the number of smallest packs that must be rolled up for geometry.
///
/// Counts are interpreted by object count, matching `git repack
/// --geometric`. Zero means the inventory already satisfies the invariant.
#[must_use]
pub fn geometric_repack_cut(object_counts: &[u64], factor: u64) -> usize {
    if factor < 2 || object_counts.len() < 2 {
        return 0;
    }
    let mut counts = object_counts.to_vec();
    counts.sort_unstable_by(|left, right| right.cmp(left));
    if counts
        .windows(2)
        .all(|pair| pair[0] >= pair[1].saturating_mul(factor))
    {
        return 0;
    }
    let prefix_is_geometric = |end: usize| {
        counts[..end]
            .windows(2)
            .all(|pair| pair[0] >= pair[1].saturating_mul(factor))
    };
    let mut rolled_objects = counts[counts.len() - 1];
    for cut in (1..counts.len()).rev() {
        if prefix_is_geometric(cut) && counts[cut - 1] >= rolled_objects.saturating_mul(factor) {
            return counts.len() - cut;
        }
        rolled_objects = rolled_objects.saturating_add(counts[cut - 1]);
    }
    counts.len()
}

/// Return the smallest suffix worth coalescing during background maintenance.
///
/// `weights` are sorted internally in descending order, normally using
/// verified compressed pack bytes. The smallest tier is promoted only after it
/// has accumulated enough weight to be comparable with its next tier, and the
/// largest pack is left untouched whenever a lower-tier promotion is possible.
/// Every lower tier is inspected, so a stable tiny tail cannot hide a collision
/// between larger packs accumulated since the previous maintenance pass.
/// Two packs are consolidated only when the smaller pack has reached the next
/// tier; a tiny tail must not rewrite the repository-sized pack.
#[must_use]
pub fn incremental_repack_cut(weights: &[u64], factor: u64) -> usize {
    if factor < 2 || weights.len() < 2 {
        return 0;
    }
    let mut weights = weights.to_vec();
    weights.sort_unstable_by(|left, right| right.cmp(left));

    if weights.len() == 2 {
        return if weights[1].saturating_mul(factor) > weights[0] {
            2
        } else {
            0
        };
    }

    let Some(mut start) = (1..weights.len() - 1)
        .find(|index| weights[*index] < weights[*index + 1].saturating_mul(factor))
    else {
        return 0;
    };
    let mut selected_weight = weights[start..]
        .iter()
        .copied()
        .fold(0_u64, u64::saturating_add);
    while start > 1 && selected_weight.saturating_mul(factor) > weights[start - 1] {
        start -= 1;
        selected_weight = selected_weight.saturating_add(weights[start]);
    }
    weights.len() - start
}

/// Consolidates source packs using Git's geometric pack policy.
pub fn repack_repository_geometric(
    sources: &[RepackSource],
    refs: &BTreeSet<String>,
) -> Result<GeometricRepackedRepository, RepackError> {
    if refs.is_empty() {
        return Err(RepackError::EmptyRefs);
    }
    let workspace =
        tempfile::tempdir().map_err(|source| io_error("create repack workspace", source))?;
    let source_git = workspace.path().join("source.git");
    initialize_bare_repository(&source_git)?;
    let pack_dir = source_git.join("objects/pack");
    for source in sources {
        validate_source(source)?;
        let installed = install_pack_file_from_path(
            &pack_dir,
            &source.path,
            &source.canonical_id,
            source.size,
            false,
        )?;
        let locations =
            PackLocationIter::open(&installed.idx_path, &installed.rev_path, source.size)?;
        if locations.object_count() != source.object_count {
            return Err(RepackError::SourceIntegrity {
                pack_id: source.canonical_id.clone(),
                reason: format!(
                    "index has {} objects but manifest records {}",
                    locations.object_count(),
                    source.object_count
                ),
            });
        }
    }
    pin_refs_and_fsck(&source_git, refs, "validate source repository")?;
    run_git(
        Command::new("git")
            .arg(format!("--git-dir={}", source_git.display()))
            .arg("repack")
            .arg("-q")
            .arg("-d")
            .arg("-g")
            .arg("2")
            .arg("--depth=64"),
        "geometrically repack source repository",
    )?;

    let source_ids = sources
        .iter()
        .map(|source| source.canonical_id.as_str())
        .collect::<BTreeSet<_>>();
    let mut pack_paths = Vec::new();
    for entry in std::fs::read_dir(&pack_dir)
        .map_err(|source| io_error(format!("read {}", pack_dir.display()), source))?
    {
        let path = entry
            .map_err(|source| io_error(format!("read entry in {}", pack_dir.display()), source))?
            .path();
        if path
            .extension()
            .is_some_and(|extension| extension == "pack")
        {
            pack_paths.push(path);
        }
    }
    pack_paths.sort_unstable();
    if pack_paths.is_empty() {
        return Err(RepackError::SourceIntegrity {
            pack_id: "geometric-repack".to_owned(),
            reason: "geometric repack produced no pack files".to_owned(),
        });
    }

    let mut packs = Vec::with_capacity(pack_paths.len());
    for pack_path in pack_paths {
        let index_path = pack_path.with_extension("idx");
        let reverse_index_path = pack_path.with_extension("rev");
        if !reverse_index_path.is_file() {
            write_pack_reverse_index(&index_path, &reverse_index_path)?;
        }
        if !index_path.is_file() || !reverse_index_path.is_file() {
            return Err(RepackError::SourceIntegrity {
                pack_id: pack_path.display().to_string(),
                reason: "geometric repack did not produce complete pack indexes".to_owned(),
            });
        }
        let pack_size = std::fs::metadata(&pack_path)
            .map_err(|source| io_error(format!("stat {}", pack_path.display()), source))?
            .len();
        let locations = PackLocationIter::open(&index_path, &reverse_index_path, pack_size)?;
        let object_count = locations.object_count();
        let git_sha1 = locations.pack_checksum().to_string();
        run_git(
            Command::new("git")
                .arg("verify-pack")
                .arg("-v")
                .arg(&index_path)
                .stdout(Stdio::null()),
            "verify geometrically repacked pack",
        )?;
        let (pack_hash, hashed_pack_size) = hash_file(&pack_path)?;
        if hashed_pack_size != pack_size {
            return Err(RepackError::SourceIntegrity {
                pack_id: pack_path.display().to_string(),
                reason: "pack changed during geometric validation".to_owned(),
            });
        }
        let pack_id = blake3::Hash::from_bytes(pack_hash).to_hex().to_string();
        let (index_hash, index_size) = hash_file(&index_path)?;
        let (reverse_index_hash, reverse_index_size) = hash_file(&reverse_index_path)?;
        packs.push(GeometricRepackedPack {
            pack_path,
            index_path,
            reverse_index_path,
            pack_id: pack_id.clone(),
            pack_hash,
            pack_size,
            index_hash,
            index_size,
            reverse_index_hash,
            reverse_index_size,
            object_count,
            git_sha1,
            is_new: !source_ids.contains(pack_id.as_str()),
        });
    }

    let replacement_paths = packs
        .iter()
        .map(|pack| {
            (
                pack.pack_path.as_path(),
                pack.index_path.as_path(),
                pack.reverse_index_path.as_path(),
            )
        })
        .collect::<Vec<_>>();
    validate_replacement_packs(workspace.path(), refs, &replacement_paths)?;
    Ok(GeometricRepackedRepository {
        _workspace: workspace,
        packs,
    })
}

/// Consolidate exactly the supplied packs while preserving their object set.
///
/// This is the object-store maintenance primitive: callers select the
/// geometric roll-up suffix and leave stable large packs remote. Installed Git
/// packs are self-contained, so Git can consume their verified pack basenames
/// directly without downloading or serializing an additional OID list. The
/// generated pack is still compared with the source object universe before it
/// leaves this function.
pub fn consolidate_pack_suffix(
    sources: &[RepackSource],
) -> Result<GeometricRepackedRepository, RepackError> {
    let concurrency = std::thread::available_parallelism()
        .map_or(DEFAULT_REPACK_INDEX_CONCURRENCY, |parallelism| {
            parallelism.get().min(DEFAULT_REPACK_INDEX_CONCURRENCY)
        });
    consolidate_pack_suffix_with_concurrency(sources, concurrency)
}

/// Consolidate selected packs with bounded local index parallelism.
///
/// A zero `index_concurrency` value is treated as one. The source bodies are
/// independent files, so indexing them concurrently shortens the local
/// installation phase without changing the order used by Git pack-objects.
pub fn consolidate_pack_suffix_with_concurrency(
    sources: &[RepackSource],
    index_concurrency: usize,
) -> Result<GeometricRepackedRepository, RepackError> {
    if sources.len() < 2 {
        return Err(RepackError::SourceIntegrity {
            pack_id: "geometric-repack".to_owned(),
            reason: "geometric consolidation requires at least two source packs".to_owned(),
        });
    }
    let mut source_ids = BTreeSet::new();
    for source in sources {
        if !source_ids.insert(source.canonical_id.as_str()) {
            return Err(RepackError::SourceIntegrity {
                pack_id: source.canonical_id.clone(),
                reason: "duplicate source pack id".to_owned(),
            });
        }
    }
    let workspace =
        tempfile::tempdir().map_err(|source| io_error("create repack workspace", source))?;
    let source_git = workspace.path().join("source.git");
    initialize_bare_repository(&source_git)?;
    let pack_dir = source_git.join("objects/pack");
    let install_started = Instant::now();
    let (mut source_oids, source_indexes) =
        install_source_packs(&pack_dir, sources, index_concurrency)?;
    tracing::debug!(
        source_pack_count = sources.len(),
        index_concurrency = index_concurrency.max(1).min(sources.len()),
        elapsed_ms = install_started.elapsed().as_millis() as u64,
        "installed source packs for consolidation"
    );
    // Selected suffixes may reference stable packs outside this operation;
    // validate each selected pack's own body and index without requiring a
    // complete repository graph.
    let verify_started = Instant::now();
    for index_batch in source_indexes.chunks(MAX_VERIFY_PACKS_PER_COMMAND) {
        let mut verify = Command::new("git");
        verify
            .arg("verify-pack")
            .arg("--")
            .args(index_batch)
            .stdout(Stdio::null());
        run_git(&mut verify, "verify consolidated source packs")?;
    }
    tracing::debug!(
        source_pack_count = source_indexes.len(),
        elapsed_ms = verify_started.elapsed().as_millis() as u64,
        "verified consolidated source packs"
    );
    source_oids.sort_unstable();
    source_oids.dedup();

    let pack_list = workspace.path().join("selected-packs.txt");
    let mut input = File::create(&pack_list)
        .map_err(|source| io_error(format!("create {}", pack_list.display()), source))?;
    for source in sources {
        let pack_name = format!("pack-{}.pack", source.canonical_id);
        writeln!(input, "{pack_name}")
            .map_err(|source| io_error(format!("write {}", pack_list.display()), source))?;
    }
    drop(input);
    let stdin = File::open(&pack_list)
        .map_err(|source| io_error(format!("open {}", pack_list.display()), source))?;
    let output_prefix = pack_dir.join("pack-crab-rollup");
    let pack_generation_started = Instant::now();
    run_git(
        Command::new("git")
            .arg(format!("--git-dir={}", source_git.display()))
            .arg("pack-objects")
            .arg("--quiet")
            .arg("--stdin-packs")
            .arg("--reuse-delta")
            .arg("--reuse-object")
            .arg("--delta-base-offset")
            .arg("--depth=64")
            .arg(&output_prefix)
            .stdin(Stdio::from(stdin))
            .stdout(Stdio::null()),
        "consolidate selected Git packs",
    )?;
    tracing::debug!(
        source_pack_count = sources.len(),
        elapsed_ms = pack_generation_started.elapsed().as_millis() as u64,
        "consolidated selected Git packs"
    );
    let pack_path = std::fs::read_dir(&pack_dir)
        .map_err(|source| io_error(format!("read {}", pack_dir.display()), source))?
        .filter_map(std::result::Result::ok)
        .map(|entry| entry.path())
        .find(|path| {
            path.file_name()
                .and_then(|name| name.to_str())
                .is_some_and(|name| {
                    name.starts_with("pack-crab-rollup-") && name.ends_with(".pack")
                })
        })
        .ok_or_else(|| RepackError::SourceIntegrity {
            pack_id: "geometric-repack".to_owned(),
            reason: "selected-pack consolidation produced no pack".to_owned(),
        })?;
    let generated = verified_generated_pack(pack_path, GeneratedPackValidation::Full)?;
    let mut generated_locations = PackLocationIter::open(
        generated.index_path(),
        generated.reverse_index_path(),
        generated.pack_size,
    )?;
    let mut generated_oids = Vec::<[u8; 20]>::new();
    for location in &mut generated_locations {
        let location = location?;
        let oid = location
            .oid
            .as_bytes()
            .try_into()
            .map_err(|_| RepackError::SourceIntegrity {
                pack_id: generated.pack_id.clone(),
                reason: "consolidated pack contains a non-SHA1 object".to_owned(),
            })?;
        generated_oids.push(oid);
    }
    generated_oids.sort_unstable();
    generated_oids.dedup();
    if generated_oids != source_oids {
        return Err(RepackError::SourceIntegrity {
            pack_id: generated.pack_id.clone(),
            reason: "consolidated pack does not preserve the selected object set".to_owned(),
        });
    }
    Ok(GeometricRepackedRepository {
        _workspace: workspace,
        packs: vec![generated],
    })
}

/// Join a complete pack inventory without inflating or recompressing entries.
///
/// OFS_DELTA offsets are relative to the current entry, so shifting every
/// entry in one source pack by the same amount preserves those links. Strict
/// indexing validates REF_DELTA links after all source bodies are joined.
pub fn concatenate_complete_pack_inventory(
    sources: &[RepackSource],
) -> Result<GeometricRepackedRepository, RepackError> {
    if sources.len() < 2 {
        return Err(RepackError::SourceIntegrity {
            pack_id: "complete-pack-concatenation".to_owned(),
            reason: "complete-pack concatenation requires at least two source packs".to_owned(),
        });
    }

    let workspace =
        tempfile::tempdir().map_err(|source| io_error("create concatenation workspace", source))?;
    let source_git = workspace.path().join("source.git");
    initialize_bare_repository(&source_git)?;
    let pack_dir = source_git.join("objects/pack");
    let output_path = workspace.path().join("complete-pack-concatenated.pack");
    let mut output = File::create(&output_path)
        .map_err(|source| io_error("create concatenated pack", source))?;
    let mut source_ids = BTreeSet::new();
    let mut total_objects = 0_u64;
    for source in sources {
        if !source_ids.insert(source.canonical_id.as_str()) {
            return Err(RepackError::SourceIntegrity {
                pack_id: source.canonical_id.clone(),
                reason: "duplicate source pack id".to_owned(),
            });
        }
        validate_source(source)?;
        verify_pack_file_sha1(&source.path)?;
        let mut input = File::open(&source.path)
            .map_err(|error| io_error(format!("open {}", source.path.display()), error))?;
        let mut header = [0_u8; 12];
        input
            .read_exact(&mut header)
            .map_err(|error| io_error(format!("read {} header", source.path.display()), error))?;
        let version =
            u32::from_be_bytes(header[4..8].try_into().map_err(|_| RepackError::Pack {
                source: PackError::InvalidPackFile {
                    path: source.path.clone(),
                    reason: "source pack header has an invalid version".to_owned(),
                },
            })?);
        if &header[..4] != b"PACK" || !matches!(version, 2 | 3) {
            return Err(RepackError::Pack {
                source: PackError::InvalidPackFile {
                    path: source.path.clone(),
                    reason: "source pack has an unsupported header".to_owned(),
                },
            });
        }
        let object_count = u64::from(u32::from_be_bytes(header[8..12].try_into().map_err(
            |_| RepackError::Pack {
                source: PackError::InvalidPackFile {
                    path: source.path.clone(),
                    reason: "source pack header has an invalid object count".to_owned(),
                },
            },
        )?));
        if object_count != source.object_count {
            return Err(RepackError::SourceIntegrity {
                pack_id: source.canonical_id.clone(),
                reason: format!(
                    "pack header has {object_count} objects but manifest records {}",
                    source.object_count
                ),
            });
        }
        total_objects = total_objects.checked_add(object_count).ok_or_else(|| {
            RepackError::SourceIntegrity {
                pack_id: source.canonical_id.clone(),
                reason: "concatenated pack object count overflows u32".to_owned(),
            }
        })?;
    }
    let total_objects_u32 =
        u32::try_from(total_objects).map_err(|_| RepackError::SourceIntegrity {
            pack_id: "complete-pack-concatenation".to_owned(),
            reason: "concatenated pack object count exceeds Git's pack limit".to_owned(),
        })?;
    output
        .write_all(b"PACK")
        .and_then(|_| output.write_all(&2_u32.to_be_bytes()))
        .and_then(|_| output.write_all(&total_objects_u32.to_be_bytes()))
        .map_err(|source| io_error("write concatenated pack header", source))?;

    let mut pack_sha1 = Sha1::new();
    pack_sha1.update(b"PACK");
    pack_sha1.update(2_u32.to_be_bytes());
    pack_sha1.update(total_objects_u32.to_be_bytes());
    let mut buffer = vec![0_u8; 1024 * 1024];
    for source in sources {
        let mut input = File::open(&source.path)
            .map_err(|error| io_error(format!("open {}", source.path.display()), error))?;
        let source_size = source.size;
        let body_size = source_size
            .checked_sub(32)
            .ok_or_else(|| RepackError::Pack {
                source: PackError::InvalidPackFile {
                    path: source.path.clone(),
                    reason: "source pack is too short for header and checksum".to_owned(),
                },
            })?;
        input
            .seek(std::io::SeekFrom::Start(12))
            .map_err(|error| io_error(format!("seek {} body", source.path.display()), error))?;
        let mut remaining = body_size;
        while remaining > 0 {
            let read_len = remaining.min(buffer.len() as u64) as usize;
            input
                .read_exact(&mut buffer[..read_len])
                .map_err(|error| io_error(format!("read {} body", source.path.display()), error))?;
            output
                .write_all(&buffer[..read_len])
                .map_err(|source| io_error("write concatenated pack body", source))?;
            pack_sha1.update(&buffer[..read_len]);
            remaining -= read_len as u64;
        }
    }
    let checksum: [u8; 20] = pack_sha1.finalize().into();
    output
        .write_all(&checksum)
        .and_then(|_| output.flush())
        .map_err(|source| io_error("finish concatenated pack", source))?;
    drop(output);

    let (pack_hash, pack_size) = hash_file(&output_path)?;
    let canonical_id = blake3::Hash::from_bytes(pack_hash).to_hex().to_string();
    let installed =
        install_pack_file_from_path(&pack_dir, &output_path, &canonical_id, pack_size, true)?;
    let generated = verified_generated_pack(installed.pack_path, GeneratedPackValidation::Full)?;
    if generated.object_count != total_objects {
        return Err(RepackError::SourceIntegrity {
            pack_id: generated.pack_id,
            reason: format!(
                "concatenated pack contains {} objects but sources contain {total_objects}",
                generated.object_count
            ),
        });
    }
    Ok(GeometricRepackedRepository {
        _workspace: workspace,
        packs: vec![generated],
    })
}

struct InstalledSourcePack {
    index_path: PathBuf,
    oids: Vec<[u8; 20]>,
}

fn install_source_packs(
    pack_dir: &Path,
    sources: &[RepackSource],
    index_concurrency: usize,
) -> Result<(Vec<[u8; 20]>, Vec<PathBuf>), RepackError> {
    let batch_size = index_concurrency.max(1).min(sources.len());
    let mut source_oids = Vec::new();
    let mut source_indexes = Vec::with_capacity(sources.len());
    for batch in sources.chunks(batch_size) {
        let results = std::thread::scope(|scope| {
            let handles = batch
                .iter()
                .map(|source| scope.spawn(move || install_source_pack(pack_dir, source)))
                .collect::<Vec<_>>();
            handles
                .into_iter()
                .map(|handle| handle.join())
                .collect::<Vec<_>>()
        });
        for (source, result) in batch.iter().zip(results) {
            let installed = match result {
                Ok(Ok(installed)) => installed,
                Ok(Err(error)) => return Err(error),
                Err(_) => {
                    return Err(RepackError::SourceIntegrity {
                        pack_id: source.canonical_id.clone(),
                        reason: "source pack installation worker panicked".to_owned(),
                    });
                }
            };
            source_oids.extend(installed.oids);
            source_indexes.push(installed.index_path);
        }
    }
    Ok((source_oids, source_indexes))
}

fn install_source_pack(
    pack_dir: &Path,
    source: &RepackSource,
) -> Result<InstalledSourcePack, RepackError> {
    validate_source(source)?;
    let installed = install_pack_file_from_path(
        pack_dir,
        &source.path,
        &source.canonical_id,
        source.size,
        false,
    )?;
    let mut locations =
        PackLocationIter::open(&installed.idx_path, &installed.rev_path, source.size)?;
    if locations.object_count() != source.object_count {
        return Err(RepackError::SourceIntegrity {
            pack_id: source.canonical_id.clone(),
            reason: format!(
                "index has {} objects but manifest records {}",
                locations.object_count(),
                source.object_count
            ),
        });
    }
    let mut oids = Vec::new();
    for location in &mut locations {
        let location = location?;
        let oid = location
            .oid
            .as_bytes()
            .try_into()
            .map_err(|_| RepackError::SourceIntegrity {
                pack_id: source.canonical_id.clone(),
                reason: "selected pack contains a non-SHA1 object".to_owned(),
            })?;
        oids.push(oid);
    }
    Ok(InstalledSourcePack {
        index_path: installed.idx_path,
        oids,
    })
}

/// Generates one self-contained pack for an exact set of selected objects.
///
/// The source packs are validated before Git repacks them. The generated
/// index is compared with the requested set so Git cannot silently add a
/// filtered-out object as a delta base.
pub fn repack_selected_objects(
    sources: &[RepackSource],
    selected_oids: &[gix_hash::ObjectId],
) -> Result<GeometricRepackedRepository, RepackError> {
    if sources.is_empty() {
        return Err(RepackError::SelectedObjectSet {
            pack_id: "selected-pack".to_owned(),
            reason: "no source packs were supplied".to_owned(),
        });
    }
    let selected = normalize_selected_oids(selected_oids, "selected-pack")?;

    let workspace =
        tempfile::tempdir().map_err(|source| io_error("create selected-pack workspace", source))?;
    let source_git = workspace.path().join("source.git");
    initialize_bare_repository(&source_git)?;
    let pack_dir = source_git.join("objects/pack");
    for source in sources {
        validate_source(source)?;
        install_pack_file_from_path(
            &pack_dir,
            &source.path,
            &source.canonical_id,
            source.size,
            false,
        )?;
    }

    let object_list = workspace.path().join("selected-objects.txt");
    let mut input = File::create(&object_list)
        .map_err(|source| io_error(format!("create {}", object_list.display()), source))?;
    for oid in &selected {
        writeln!(input, "{oid}")
            .map_err(|source| io_error(format!("write {}", object_list.display()), source))?;
    }
    drop(input);
    let generated = pack_selected_objects(
        &source_git,
        &pack_dir,
        &object_list,
        &selected,
        "pack-crab-selected",
        GeneratedPackValidation::Full,
    )?;
    Ok(GeometricRepackedRepository {
        _workspace: workspace,
        packs: vec![generated],
    })
}

/// Generate the exact self-contained pack for an existing shallow client's negotiation.
///
/// The source packs are one immutable repository inventory. Git evaluates the
/// requested wants and common haves with the client's shallow boundaries
/// installed, then the generated index is compared with that exact revision
/// selection so reused deltas cannot add an unauthorized object. Source packs
/// must have passed object validation before entering the committed inventory;
/// the generated transfer pack revalidates its pack, index, reverse-index, and
/// exact object-set checksums without inflating every object a second time.
pub fn repack_shallow_fetch(
    sources: &[RepackSource],
    wants: &[gix_hash::ObjectId],
    common_haves: &[gix_hash::ObjectId],
    shallow: &[gix_hash::ObjectId],
    included_tags: &[ShallowFetchTag],
    maximum_objects: usize,
) -> Result<GeometricRepackedRepository, RepackError> {
    if sources.is_empty() || wants.is_empty() || common_haves.is_empty() || shallow.is_empty() {
        return Err(RepackError::SelectedObjectSet {
            pack_id: "shallow-fetch".to_owned(),
            reason: "shallow fetch requires source packs, wants, common haves, and boundaries"
                .to_owned(),
        });
    }

    let workspace =
        tempfile::tempdir().map_err(|source| io_error("create shallow-fetch workspace", source))?;
    let source_git = workspace.path().join("source.git");
    initialize_bare_repository(&source_git)?;
    let pack_dir = source_git.join("objects/pack");
    let concurrency = std::thread::available_parallelism()
        .map_or(DEFAULT_REPACK_INDEX_CONCURRENCY, |parallelism| {
            parallelism.get().min(DEFAULT_REPACK_INDEX_CONCURRENCY)
        });
    let _ = install_source_packs(&pack_dir, sources, concurrency)?;

    let shallow_path = source_git.join("shallow");
    let mut shallow_file = File::create(&shallow_path)
        .map_err(|source| io_error(format!("create {}", shallow_path.display()), source))?;
    for oid in shallow {
        writeln!(shallow_file, "{oid}")
            .map_err(|source| io_error(format!("write {}", shallow_path.display()), source))?;
    }
    drop(shallow_file);

    let revisions_path = workspace.path().join("shallow-fetch-revisions.txt");
    let mut revisions = File::create(&revisions_path)
        .map_err(|source| io_error(format!("create {}", revisions_path.display()), source))?;
    for oid in wants {
        writeln!(revisions, "{oid}")
            .map_err(|source| io_error(format!("write {}", revisions_path.display()), source))?;
    }
    for oid in common_haves {
        writeln!(revisions, "^{oid}")
            .map_err(|source| io_error(format!("write {}", revisions_path.display()), source))?;
    }
    drop(revisions);

    let object_list = workspace.path().join("shallow-fetch-objects.txt");
    let revision_input = File::open(&revisions_path)
        .map_err(|source| io_error(format!("open {}", revisions_path.display()), source))?;
    let object_output = File::create(&object_list)
        .map_err(|source| io_error(format!("create {}", object_list.display()), source))?;
    run_git(
        Command::new("git")
            .arg(format!("--git-dir={}", source_git.display()))
            .args(["rev-list", "--stdin", "--objects", "--no-object-names"])
            .stdin(Stdio::from(revision_input))
            .stdout(Stdio::from(object_output)),
        "enumerate shallow fetch objects",
    )?;
    let selected = read_selected_oids(&object_list, maximum_objects, "shallow-fetch")?;
    let selected = include_reachable_tag_objects(
        &source_git,
        &object_list,
        selected,
        included_tags,
        maximum_objects,
    )?;
    let generated = pack_selected_objects(
        &source_git,
        &pack_dir,
        &object_list,
        &selected,
        "pack-crab-shallow",
        GeneratedPackValidation::Structural,
    )?;
    Ok(GeometricRepackedRepository {
        _workspace: workspace,
        packs: vec![generated],
    })
}

fn include_reachable_tag_objects(
    source_git: &Path,
    object_list: &Path,
    mut selected: Vec<gix_hash::ObjectId>,
    included_tags: &[ShallowFetchTag],
    maximum_objects: usize,
) -> Result<Vec<gix_hash::ObjectId>, RepackError> {
    let selected_set = selected.iter().copied().collect::<BTreeSet<_>>();
    let included_tags = included_tags
        .iter()
        .filter(|tag| tag.target != tag.peeled && selected_set.contains(&tag.peeled))
        .collect::<Vec<_>>();
    if included_tags.is_empty() {
        return Ok(selected);
    }

    let workspace = object_list
        .parent()
        .ok_or_else(|| RepackError::SelectedObjectSet {
            pack_id: "shallow-fetch".to_owned(),
            reason: "shallow fetch object list has no parent directory".to_owned(),
        })?;
    let revisions_path = workspace.join("shallow-fetch-tag-revisions.txt");
    let mut revisions = File::create(&revisions_path)
        .map_err(|source| io_error(format!("create {}", revisions_path.display()), source))?;
    for tag in included_tags {
        writeln!(revisions, "{}\n^{}", tag.target, tag.peeled)
            .map_err(|source| io_error(format!("write {}", revisions_path.display()), source))?;
    }
    drop(revisions);

    let tag_objects_path = workspace.join("shallow-fetch-tag-objects.txt");
    let revision_input = File::open(&revisions_path)
        .map_err(|source| io_error(format!("open {}", revisions_path.display()), source))?;
    let object_output = File::create(&tag_objects_path)
        .map_err(|source| io_error(format!("create {}", tag_objects_path.display()), source))?;
    run_git(
        Command::new("git")
            .arg(format!("--git-dir={}", source_git.display()))
            .args(["rev-list", "--stdin", "--objects", "--no-object-names"])
            .stdin(Stdio::from(revision_input))
            .stdout(Stdio::from(object_output)),
        "enumerate shallow fetch tag objects",
    )?;
    let remaining = maximum_objects.saturating_sub(selected.len());
    let tag_objects = read_selected_oids(&tag_objects_path, remaining, "shallow-fetch-tags")?;
    let mut selected_set = selected_set;
    let mut object_list = std::fs::OpenOptions::new()
        .append(true)
        .open(object_list)
        .map_err(|source| io_error("open shallow fetch object list for tags", source))?;
    for oid in tag_objects {
        if selected_set.insert(oid) {
            writeln!(object_list, "{oid}")
                .map_err(|source| io_error("append shallow fetch tag object", source))?;
            selected.push(oid);
        }
    }
    normalize_selected_oids(&selected, "shallow-fetch")
}

fn normalize_selected_oids(
    selected_oids: &[gix_hash::ObjectId],
    pack_id: &str,
) -> Result<Vec<gix_hash::ObjectId>, RepackError> {
    let mut selected = selected_oids.to_vec();
    if selected.is_empty()
        || selected
            .iter()
            .any(|oid| oid.as_bytes().len() != std::mem::size_of::<[u8; 20]>())
    {
        return Err(RepackError::SelectedObjectSet {
            pack_id: pack_id.to_owned(),
            reason: "selected object IDs must be non-empty SHA-1 IDs".to_owned(),
        });
    }
    selected.sort_unstable();
    if selected.windows(2).any(|pair| pair[0] == pair[1]) {
        return Err(RepackError::SelectedObjectSet {
            pack_id: pack_id.to_owned(),
            reason: "selected object IDs must be unique".to_owned(),
        });
    }
    Ok(selected)
}

fn read_selected_oids(
    path: &Path,
    maximum_objects: usize,
    pack_id: &str,
) -> Result<Vec<gix_hash::ObjectId>, RepackError> {
    let file =
        File::open(path).map_err(|source| io_error(format!("open {}", path.display()), source))?;
    let mut selected = Vec::new();
    for line in BufReader::new(file).lines() {
        if selected.len() >= maximum_objects {
            return Err(RepackError::SelectedObjectSet {
                pack_id: pack_id.to_owned(),
                reason: format!("selected object count exceeds {maximum_objects}"),
            });
        }
        let line = line.map_err(|source| io_error(format!("read {}", path.display()), source))?;
        let oid = gix_hash::ObjectId::from_hex(line.as_bytes()).map_err(|error| {
            RepackError::SelectedObjectSet {
                pack_id: pack_id.to_owned(),
                reason: format!("Git returned an invalid object ID: {error}"),
            }
        })?;
        selected.push(oid);
    }
    normalize_selected_oids(&selected, pack_id)
}

fn pack_selected_objects(
    source_git: &Path,
    pack_dir: &Path,
    object_list: &Path,
    selected: &[gix_hash::ObjectId],
    output_name: &str,
    validation: GeneratedPackValidation,
) -> Result<GeometricRepackedPack, RepackError> {
    let stdin = File::open(object_list)
        .map_err(|source| io_error(format!("open {}", object_list.display()), source))?;
    let output_prefix = pack_dir.join(output_name);
    run_git(
        Command::new("git")
            .arg(format!("--git-dir={}", source_git.display()))
            .arg("pack-objects")
            .arg("--quiet")
            .arg("--reuse-delta")
            .arg("--reuse-object")
            .arg("--delta-base-offset")
            .arg("--depth=64")
            .arg(&output_prefix)
            .stdin(Stdio::from(stdin))
            .stdout(Stdio::null()),
        "pack selected Git objects",
    )?;
    let output_prefix_name = format!("{output_name}-");
    let pack_path = std::fs::read_dir(pack_dir)
        .map_err(|source| io_error(format!("read {}", pack_dir.display()), source))?
        .filter_map(std::result::Result::ok)
        .map(|entry| entry.path())
        .find(|path| {
            path.file_name()
                .and_then(|name| name.to_str())
                .is_some_and(|name| {
                    name.starts_with(&output_prefix_name) && name.ends_with(".pack")
                })
        })
        .ok_or_else(|| RepackError::SelectedObjectSet {
            pack_id: "selected-pack".to_owned(),
            reason: "selected-object packing produced no pack".to_owned(),
        })?;
    let generated = verified_generated_pack(pack_path, validation)?;
    let mut generated_locations = PackLocationIter::open(
        &generated.index_path,
        &generated.reverse_index_path,
        generated.pack_size,
    )?;
    let mut generated_oids = Vec::<[u8; 20]>::new();
    for location in &mut generated_locations {
        let location = location?;
        let oid =
            location
                .oid
                .as_bytes()
                .try_into()
                .map_err(|_| RepackError::SelectedObjectSet {
                    pack_id: generated.pack_id.clone(),
                    reason: "generated pack contains a non-SHA1 object".to_owned(),
                })?;
        generated_oids.push(oid);
    }
    generated_oids.sort_unstable();
    let selected_matches = generated_oids.len() == selected.len()
        && generated_oids
            .iter()
            .zip(selected)
            .all(|(generated, selected)| selected.as_bytes() == generated);
    if !selected_matches {
        return Err(RepackError::SelectedObjectSet {
            pack_id: generated.pack_id,
            reason: format!(
                "generated {} objects for {} requested objects",
                generated_oids.len(),
                selected.len()
            ),
        });
    }
    Ok(generated)
}

fn verified_generated_pack(
    pack_path: PathBuf,
    validation: GeneratedPackValidation,
) -> Result<GeometricRepackedPack, RepackError> {
    let index_path = pack_path.with_extension("idx");
    let reverse_index_path = pack_path.with_extension("rev");
    if !reverse_index_path.is_file() {
        write_pack_reverse_index(&index_path, &reverse_index_path)?;
    }
    if !index_path.is_file() || !reverse_index_path.is_file() {
        return Err(RepackError::SourceIntegrity {
            pack_id: pack_path.display().to_string(),
            reason: "consolidated pack is missing an index or reverse index".to_owned(),
        });
    }
    let pack_size = std::fs::metadata(&pack_path)
        .map_err(|source| io_error(format!("stat {}", pack_path.display()), source))?
        .len();
    let locations = PackLocationIter::open(&index_path, &reverse_index_path, pack_size)?;
    let object_count = locations.object_count();
    let git_sha1 = locations.pack_checksum().to_string();
    let (trailer, pack_hash, hashed_size) = verify_and_hash_pack_file(&pack_path)?;
    if trailer != git_sha1 {
        return Err(RepackError::SourceIntegrity {
            pack_id: pack_path.display().to_string(),
            reason: "generated pack index checksum does not match its pack trailer".to_owned(),
        });
    }
    if matches!(validation, GeneratedPackValidation::Full) {
        run_git(
            Command::new("git")
                .arg("verify-pack")
                .arg("-v")
                .arg(&index_path)
                .stdout(Stdio::null()),
            "verify consolidated Git pack",
        )?;
    }
    if hashed_size != pack_size {
        return Err(RepackError::SourceIntegrity {
            pack_id: pack_path.display().to_string(),
            reason: "consolidated pack changed during validation".to_owned(),
        });
    }
    let (index_hash, index_size) = hash_file(&index_path)?;
    let (reverse_index_hash, reverse_index_size) = hash_file(&reverse_index_path)?;
    Ok(GeometricRepackedPack {
        pack_path,
        index_path,
        reverse_index_path,
        pack_id: blake3::Hash::from_bytes(pack_hash).to_hex().to_string(),
        pack_hash,
        pack_size,
        index_hash,
        index_size,
        reverse_index_hash,
        reverse_index_size,
        object_count,
        git_sha1,
        is_new: true,
    })
}

fn validate_source(source: &RepackSource) -> Result<(), RepackError> {
    let (hash, size) = hash_file(&source.path)?;
    if size != source.size {
        return Err(RepackError::SourceIntegrity {
            pack_id: source.canonical_id.clone(),
            reason: format!(
                "download has {size} bytes but manifest records {}",
                source.size
            ),
        });
    }
    let actual = blake3::Hash::from_bytes(hash).to_hex().to_string();
    if actual != source.canonical_id {
        return Err(RepackError::SourceIntegrity {
            pack_id: source.canonical_id.clone(),
            reason: format!("Blake3 identifier is {actual}"),
        });
    }
    Ok(())
}

fn validate_replacement_packs(
    workspace: &Path,
    refs: &BTreeSet<String>,
    packs: &[(&Path, &Path, &Path)],
) -> Result<(), RepackError> {
    let repository = workspace.join("validation.git");
    initialize_bare_repository(&repository)?;
    let pack_dir = repository.join("objects/pack");
    for (index, (pack_path, index_path, reverse_index_path)) in packs.iter().enumerate() {
        let prefix = format!("pack-replacement-{index}");
        for (source, target) in [
            (*pack_path, pack_dir.join(format!("{prefix}.pack"))),
            (*index_path, pack_dir.join(format!("{prefix}.idx"))),
            (*reverse_index_path, pack_dir.join(format!("{prefix}.rev"))),
        ] {
            std::fs::copy(source, &target)
                .map_err(|error| io_error(format!("copy {}", source.display()), error))?;
        }
    }
    pin_refs_and_fsck(&repository, refs, "validate replacement repository")
}

fn pin_refs_and_fsck(
    repository: &Path,
    refs: &BTreeSet<String>,
    operation: &'static str,
) -> Result<(), RepackError> {
    for (index, oid) in refs.iter().enumerate() {
        let name = format!("refs/heads/crab-repack-{index}");
        run_git(
            Command::new("git")
                .arg(format!("--git-dir={}", repository.display()))
                .arg("update-ref")
                .arg(&name)
                .arg(oid),
            operation,
        )?;
        if index == 0 {
            run_git(
                Command::new("git")
                    .arg(format!("--git-dir={}", repository.display()))
                    .arg("symbolic-ref")
                    .arg("HEAD")
                    .arg(&name),
                operation,
            )?;
        }
    }
    run_git(
        Command::new("git")
            .arg(format!("--git-dir={}", repository.display()))
            .arg("fsck")
            .arg("--strict")
            .arg("--full")
            .arg("--no-reflogs"),
        operation,
    )
}

fn initialize_bare_repository(path: &Path) -> Result<(), RepackError> {
    run_git(
        Command::new("git")
            .arg("init")
            .arg("--bare")
            .arg("--quiet")
            .arg(path),
        "initialize temporary bare repository",
    )
}

fn run_git(command: &mut Command, operation: &'static str) -> Result<(), RepackError> {
    // Every repack subprocess targets an explicit temporary repository or pack.
    // Local repository overrides could redirect object reads or replace the
    // installed shallow boundary, invalidating the pinned-inventory proof.
    for variable in [
        "GIT_ALTERNATE_OBJECT_DIRECTORIES",
        "GIT_CONFIG",
        "GIT_CONFIG_PARAMETERS",
        "GIT_CONFIG_COUNT",
        "GIT_OBJECT_DIRECTORY",
        "GIT_DIR",
        "GIT_WORK_TREE",
        "GIT_IMPLICIT_WORK_TREE",
        "GIT_GRAFT_FILE",
        "GIT_INDEX_FILE",
        "GIT_NO_REPLACE_OBJECTS",
        "GIT_REPLACE_REF_BASE",
        "GIT_PREFIX",
        "GIT_SHALLOW_FILE",
        "GIT_COMMON_DIR",
        "GIT_NAMESPACE",
    ] {
        command.env_remove(variable);
    }
    let status = command
        .status()
        .map_err(|source| io_error(format!("run {operation}"), source))?;
    if status.success() {
        Ok(())
    } else {
        Err(RepackError::Git { operation, status })
    }
}

fn hash_file(path: &Path) -> Result<([u8; 32], u64), RepackError> {
    let mut file =
        File::open(path).map_err(|source| io_error(format!("open {}", path.display()), source))?;
    let size = file
        .metadata()
        .map_err(|source| io_error(format!("stat {}", path.display()), source))?
        .len();
    let mut hasher = blake3::Hasher::new();
    io::copy(&mut file, &mut hasher)
        .map_err(|source| io_error(format!("hash {}", path.display()), source))?;
    Ok((*hasher.finalize().as_bytes(), size))
}

fn io_error(context: impl Into<String>, source: io::Error) -> RepackError {
    RepackError::Io {
        context: context.into(),
        source,
    }
}

#[cfg(test)]
mod tests {
    use std::process::Output;

    use super::*;

    #[test]
    fn geometric_cut_leaves_valid_large_prefix_untouched() {
        assert_eq!(geometric_repack_cut(&[1_000, 100, 60, 1], 2), 3);
    }

    #[test]
    fn geometric_cut_skips_an_already_geometric_inventory() {
        assert_eq!(geometric_repack_cut(&[20, 100, 40], 2), 0);
    }

    #[test]
    fn geometric_cut_rolls_every_pack_when_no_stable_prefix_exists() {
        assert_eq!(geometric_repack_cut(&[100, 60, 1], 2), 3);
    }

    #[test]
    fn incremental_cut_waits_for_a_lower_pack_tier_before_rewriting_large_packs() {
        assert_eq!(incremental_repack_cut(&[900, 9], 2), 0);
        assert_eq!(incremental_repack_cut(&[900, 700, 9], 2), 0);
        assert_eq!(incremental_repack_cut(&[900, 700, 9, 9], 2), 2);
        assert_eq!(incremental_repack_cut(&[900, 700], 2), 2);
    }

    #[test]
    fn incremental_cut_keeps_the_largest_pack_out_of_lower_tier_promotions() {
        assert_eq!(incremental_repack_cut(&[900, 700, 600, 400], 2), 3);
    }

    #[test]
    fn incremental_cut_scans_past_a_stable_tiny_tail() {
        assert_eq!(incremental_repack_cut(&[1_000_000, 100, 60, 1], 2), 3);
        assert_eq!(
            incremental_repack_cut(&[1_000_000, 900, 600, 100, 60, 1], 2),
            5
        );
    }

    #[test]
    #[expect(
        clippy::same_item_push,
        reason = "the test models one identical tiny pack per developer push"
    )]
    fn incremental_cut_keeps_tiny_pushes_logarithmic() {
        let mut packs = vec![1_000_000_u64];
        for _ in 0..1_000 {
            packs.push(1);
            let cut = incremental_repack_cut(&packs, 2);
            if cut != 0 {
                let split = packs.len() - cut;
                let merged = packs[split..].iter().copied().sum();
                packs.truncate(split);
                packs.push(merged);
            }
        }

        assert_eq!(packs.iter().copied().sum::<u64>(), 1_001_000);
        assert_eq!(packs.iter().copied().max(), Some(1_000_000));
        assert!(packs.len() <= 12, "pack count grew to {}", packs.len());
    }

    #[test]
    fn selected_object_repack_rejects_duplicate_ids_before_io() {
        let oid = gix_hash::ObjectId::from([7_u8; 20]);
        let source = RepackSource {
            canonical_id: "source".to_owned(),
            path: PathBuf::new(),
            size: 0,
            object_count: 0,
        };

        let error = repack_selected_objects(&[source], &[oid, oid]).unwrap_err();
        assert!(matches!(
            error,
            RepackError::SelectedObjectSet { reason, .. }
                if reason == "selected object IDs must be unique"
        ));
    }

    #[test]
    fn shallow_fetch_repack_includes_new_side_history_but_not_shallow_parent()
    -> Result<(), RepackError> {
        let root = tempfile::tempdir().map_err(|source| io_error("create test root", source))?;
        let repository = root.path().join("repository");
        run_git(
            Command::new("git")
                .arg("init")
                .arg("--quiet")
                .arg(&repository),
            "initialize shallow-fetch test repository",
        )?;
        run_git(
            Command::new("git").arg("-C").arg(&repository).args([
                "config",
                "user.name",
                "Crab Test",
            ]),
            "configure shallow-fetch test name",
        )?;
        run_git(
            Command::new("git").arg("-C").arg(&repository).args([
                "config",
                "user.email",
                "crab@example.invalid",
            ]),
            "configure shallow-fetch test email",
        )?;

        std::fs::write(repository.join("root.txt"), b"root\n")
            .map_err(|source| io_error("write root file", source))?;
        commit_all(&repository, "root")?;
        let root_commit = git_output(
            Command::new("git")
                .arg("-C")
                .arg(&repository)
                .args(["rev-parse", "HEAD"]),
            "resolve root commit",
        )?;
        let main_branch = git_output(
            Command::new("git")
                .arg("-C")
                .arg(&repository)
                .args(["branch", "--show-current"]),
            "resolve main branch",
        )?;

        std::fs::write(repository.join("main-parent.txt"), b"main parent\n")
            .map_err(|source| io_error("write main parent file", source))?;
        commit_all(&repository, "main parent")?;
        let shallow_parent = git_output(
            Command::new("git")
                .arg("-C")
                .arg(&repository)
                .args(["rev-parse", "HEAD"]),
            "resolve shallow parent",
        )?;
        std::fs::write(repository.join("shallow-tip.txt"), b"shallow tip\n")
            .map_err(|source| io_error("write shallow tip file", source))?;
        commit_all(&repository, "shallow tip")?;
        let shallow_tip = git_output(
            Command::new("git")
                .arg("-C")
                .arg(&repository)
                .args(["rev-parse", "HEAD"]),
            "resolve shallow tip",
        )?;

        run_git(
            Command::new("git").arg("-C").arg(&repository).args([
                "checkout",
                "--quiet",
                "-b",
                "side",
                &root_commit,
            ]),
            "create side branch",
        )?;
        std::fs::write(repository.join("side.txt"), b"side history\n")
            .map_err(|source| io_error("write side file", source))?;
        commit_all(&repository, "side history")?;
        let side_commit = git_output(
            Command::new("git")
                .arg("-C")
                .arg(&repository)
                .args(["rev-parse", "HEAD"]),
            "resolve side commit",
        )?;
        run_git(
            Command::new("git").arg("-C").arg(&repository).args([
                "tag",
                "--annotate",
                "--message=included tag",
                "included-tag",
                &side_commit,
            ]),
            "create included shallow-fetch tag",
        )?;
        let included_tag = git_output(
            Command::new("git")
                .arg("-C")
                .arg(&repository)
                .args(["rev-parse", "included-tag^{tag}"]),
            "resolve included tag object",
        )?;
        run_git(
            Command::new("git").arg("-C").arg(&repository).args([
                "tag",
                "--annotate",
                "--message=excluded tag",
                "excluded-tag",
                &shallow_parent,
            ]),
            "create excluded shallow-fetch tag",
        )?;
        let excluded_tag = git_output(
            Command::new("git")
                .arg("-C")
                .arg(&repository)
                .args(["rev-parse", "excluded-tag^{tag}"]),
            "resolve excluded tag object",
        )?;
        run_git(
            Command::new("git")
                .arg("-C")
                .arg(&repository)
                .arg("checkout")
                .arg("--quiet")
                .arg(&main_branch),
            "restore main branch",
        )?;
        run_git(
            Command::new("git").arg("-C").arg(&repository).args([
                "merge",
                "--quiet",
                "--no-ff",
                "-m",
                "merge side",
                "side",
            ]),
            "merge side history",
        )?;
        let want = git_output(
            Command::new("git")
                .arg("-C")
                .arg(&repository)
                .args(["rev-parse", "HEAD"]),
            "resolve merged tip",
        )?;

        let source = source_descriptor(snapshot_pack(
            &repository,
            root.path(),
            "shallow-fetch-source",
        )?)?;
        let oid = |value: &str| {
            gix_hash::ObjectId::from_hex(value.as_bytes()).map_err(|error| {
                io_error(
                    "decode shallow-fetch object ID",
                    io::Error::new(io::ErrorKind::InvalidData, error),
                )
            })
        };
        let generated = repack_shallow_fetch(
            &[source],
            &[oid(&want)?],
            &[oid(&shallow_tip)?],
            &[oid(&shallow_tip)?],
            &[
                ShallowFetchTag {
                    target: oid(&included_tag)?,
                    peeled: oid(&side_commit)?,
                },
                ShallowFetchTag {
                    target: oid(&excluded_tag)?,
                    peeled: oid(&shallow_parent)?,
                },
            ],
            100,
        )?;
        let pack = generated
            .packs()
            .first()
            .ok_or_else(|| RepackError::SelectedObjectSet {
                pack_id: "shallow-fetch".to_owned(),
                reason: "test generated no pack".to_owned(),
            })?;
        let mut locations =
            PackLocationIter::open(pack.index_path(), pack.reverse_index_path(), pack.pack_size)?;
        let objects = locations
            .by_ref()
            .map(|location| location.map(|location| location.oid))
            .collect::<std::result::Result<Vec<_>, _>>()?;

        assert!(objects.contains(&oid(&want)?));
        assert!(objects.contains(&oid(&side_commit)?));
        assert!(objects.contains(&oid(&included_tag)?));
        assert!(!objects.contains(&oid(&shallow_parent)?));
        assert!(!objects.contains(&oid(&excluded_tag)?));
        Ok(())
    }

    #[test]
    fn geometric_repack_preserves_complete_ref_object_graph() -> Result<(), RepackError> {
        let root = tempfile::tempdir().map_err(|source| io_error("create test root", source))?;
        let repository = root.path().join("repository");
        run_git(
            Command::new("git")
                .arg("init")
                .arg("--quiet")
                .arg(&repository),
            "initialize test repository",
        )?;
        run_git(
            Command::new("git").arg("-C").arg(&repository).args([
                "config",
                "user.name",
                "Crab Test",
            ]),
            "configure test name",
        )?;
        run_git(
            Command::new("git").arg("-C").arg(&repository).args([
                "config",
                "user.email",
                "crab@example.invalid",
            ]),
            "configure test email",
        )?;
        std::fs::write(repository.join("first.txt"), b"first contents\n")
            .map_err(|source| io_error("write first file", source))?;
        commit_all(&repository, "first")?;
        let first = snapshot_pack(&repository, root.path(), "first")?;
        std::fs::write(repository.join("second.txt"), b"second contents\n")
            .map_err(|source| io_error("write second file", source))?;
        commit_all(&repository, "second")?;
        let second = snapshot_pack(&repository, root.path(), "second")?;
        let tip = git_output(
            Command::new("git")
                .arg("-C")
                .arg(&repository)
                .args(["rev-parse", "HEAD"]),
            "resolve test tip",
        )?;
        let refs = BTreeSet::from([tip]);
        let sources = [source_descriptor(first)?, source_descriptor(second)?];

        let geometric = repack_repository_geometric(&sources, &refs)?;
        assert!(!geometric.packs().is_empty());
        assert!(geometric.packs().len() <= sources.len());
        for pack in geometric.packs() {
            assert!(pack.pack_path().is_file());
            assert!(pack.index_path().is_file());
            assert!(pack.reverse_index_path().is_file());
        }
        let selected = consolidate_pack_suffix_with_concurrency(&sources, 2)?;
        assert_eq!(selected.packs().len(), 1);
        assert!(selected.packs()[0].object_count <= sources.iter().map(|s| s.object_count).sum());

        let selected_oids = git_output(
            Command::new("git")
                .arg("-C")
                .arg(&repository)
                .args(["rev-list", "--objects", "HEAD"]),
            "list selected test objects",
        )?
        .lines()
        .take(2)
        .filter_map(|line| {
            line.split_whitespace()
                .next()
                .and_then(|oid| gix_hash::ObjectId::from_hex(oid.as_bytes()).ok())
        })
        .collect::<Vec<_>>();
        assert_eq!(selected_oids.len(), 2);
        let selected = repack_selected_objects(&sources, &selected_oids)?;
        assert_eq!(selected.packs().len(), 1);
        assert_eq!(selected.packs()[0].object_count, selected_oids.len() as u64);
        Ok(())
    }

    #[test]
    fn concatenate_complete_pack_inventory_preserves_pack_objects() -> Result<(), RepackError> {
        let root = tempfile::tempdir().map_err(|source| io_error("create test root", source))?;
        let repository = root.path().join("repository.git");
        run_git(
            Command::new("git")
                .arg("init")
                .arg("--bare")
                .arg("--quiet")
                .arg(&repository),
            "initialize concatenation test repository",
        )?;

        let repository_arg = repository.to_str().ok_or_else(|| {
            io_error(
                "encode concatenation test repository path",
                io::Error::new(io::ErrorKind::InvalidData, "path is not UTF-8"),
            )
        })?;
        let first_data = vec![b'a'; 64 * 1024];
        let first_oid = String::from_utf8(git_with_stdin(
            &["--git-dir", repository_arg, "hash-object", "-w", "--stdin"],
            &first_data,
        ))
        .map_err(|error| {
            io_error(
                "decode first concatenation test object",
                io::Error::new(io::ErrorKind::InvalidData, error),
            )
        })?
        .trim()
        .to_owned();
        let mut first_delta_data = first_data.clone();
        first_delta_data[1_024] = b'b';
        let first_delta_oid = String::from_utf8(git_with_stdin(
            &["--git-dir", repository_arg, "hash-object", "-w", "--stdin"],
            &first_delta_data,
        ))
        .map_err(|error| {
            io_error(
                "decode first delta concatenation test object",
                io::Error::new(io::ErrorKind::InvalidData, error),
            )
        })?
        .trim()
        .to_owned();
        let second_oid = String::from_utf8(git_with_stdin(
            &["--git-dir", repository_arg, "hash-object", "-w", "--stdin"],
            b"second concatenation object\n",
        ))
        .map_err(|error| {
            io_error(
                "decode second concatenation test object",
                io::Error::new(io::ErrorKind::InvalidData, error),
            )
        })?
        .trim()
        .to_owned();

        let first_prefix = root.path().join("first");
        let first_prefix_arg = first_prefix.to_str().ok_or_else(|| {
            io_error(
                "encode first concatenation pack path",
                io::Error::new(io::ErrorKind::InvalidData, "path is not UTF-8"),
            )
        })?;
        let first_hash = String::from_utf8(git_with_stdin(
            &[
                "--git-dir",
                repository_arg,
                "pack-objects",
                "--delta-base-offset",
                first_prefix_arg,
            ],
            format!("{first_oid}\n{first_delta_oid}\n").as_bytes(),
        ))
        .map_err(|error| {
            io_error(
                "decode first concatenation pack hash",
                io::Error::new(io::ErrorKind::InvalidData, error),
            )
        })?
        .trim()
        .to_owned();
        let second_prefix = root.path().join("second");
        let second_prefix_arg = second_prefix.to_str().ok_or_else(|| {
            io_error(
                "encode second concatenation pack path",
                io::Error::new(io::ErrorKind::InvalidData, "path is not UTF-8"),
            )
        })?;
        let second_hash = String::from_utf8(git_with_stdin(
            &[
                "--git-dir",
                repository_arg,
                "pack-objects",
                "--delta-base-offset",
                second_prefix_arg,
            ],
            format!("{second_oid}\n").as_bytes(),
        ))
        .map_err(|error| {
            io_error(
                "decode second concatenation pack hash",
                io::Error::new(io::ErrorKind::InvalidData, error),
            )
        })?
        .trim()
        .to_owned();
        let first = source_descriptor(root.path().join(format!("first-{first_hash}.pack")))?;
        let first_pack_info = git_output(
            Command::new("git")
                .arg("verify-pack")
                .arg("-v")
                .arg(first.path.with_extension("idx")),
            "inspect first concatenation test pack",
        )?;
        assert!(
            first_pack_info
                .lines()
                .any(|line| line.split_whitespace().count() >= 6),
            "first test pack should contain a delta entry"
        );
        let second = source_descriptor(root.path().join(format!("second-{second_hash}.pack")))?;

        let concatenated = concatenate_complete_pack_inventory(&[first, second])?;
        let generated =
            concatenated
                .packs()
                .first()
                .ok_or_else(|| RepackError::SourceIntegrity {
                    pack_id: "complete-pack-concatenation".to_owned(),
                    reason: "test produced no concatenated pack".to_owned(),
                })?;
        assert_eq!(generated.object_count, 3);
        let mut locations = PackLocationIter::open(
            generated.index_path(),
            generated.reverse_index_path(),
            generated.pack_size,
        )?;
        let mut actual = Vec::new();
        for location in &mut locations {
            let location = location?;
            actual.push(location.oid);
        }
        actual.sort_unstable();
        let mut expected = vec![
            gix_hash::ObjectId::from_hex(first_oid.as_bytes()).map_err(|error| {
                io_error(
                    "decode first test object ID",
                    io::Error::new(io::ErrorKind::InvalidData, error),
                )
            })?,
            gix_hash::ObjectId::from_hex(first_delta_oid.as_bytes()).map_err(|error| {
                io_error(
                    "decode first delta test object ID",
                    io::Error::new(io::ErrorKind::InvalidData, error),
                )
            })?,
            gix_hash::ObjectId::from_hex(second_oid.as_bytes()).map_err(|error| {
                io_error(
                    "decode second test object ID",
                    io::Error::new(io::ErrorKind::InvalidData, error),
                )
            })?,
        ];
        expected.sort_unstable();
        assert_eq!(actual, expected);
        Ok(())
    }

    #[test]
    fn repack_git_subprocess_ignores_repository_overrides() -> Result<(), RepackError> {
        let root = tempfile::tempdir().map_err(|source| io_error("create test root", source))?;
        let repository = root.path().join("repository");
        let mut command = Command::new("git");
        command
            .env("GIT_DIR", root.path().join("ambient.git"))
            .env("GIT_WORK_TREE", root.path().join("ambient-worktree"))
            .env("GIT_OBJECT_DIRECTORY", root.path().join("ambient-objects"))
            .env(
                "GIT_ALTERNATE_OBJECT_DIRECTORIES",
                root.path().join("ambient-alternates"),
            )
            .env("GIT_SHALLOW_FILE", root.path().join("ambient-shallow"))
            .args(["init", "--quiet"])
            .arg(&repository);

        run_git(&mut command, "initialize isolated test repository")?;

        assert!(repository.join(".git").is_dir());
        assert!(!root.path().join("ambient.git").exists());
        assert!(!root.path().join("ambient-objects").exists());
        Ok(())
    }

    fn git_with_stdin(args: &[&str], input: &[u8]) -> Vec<u8> {
        let mut child = Command::new("git")
            .args(args)
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .spawn()
            .expect("spawn git");
        child
            .stdin
            .take()
            .expect("piped git stdin")
            .write_all(input)
            .expect("write git stdin");
        let output = child.wait_with_output().expect("wait for git");
        assert!(
            output.status.success(),
            "git {args:?} failed: {}",
            String::from_utf8_lossy(&output.stderr)
        );
        output.stdout
    }

    fn commit_all(repository: &Path, message: &str) -> Result<(), RepackError> {
        run_git(
            Command::new("git")
                .arg("-C")
                .arg(repository)
                .args(["add", "."]),
            "stage test commit",
        )?;
        run_git(
            Command::new("git")
                .arg("-C")
                .arg(repository)
                .args(["commit", "--quiet", "-m", message]),
            "create test commit",
        )
    }

    fn snapshot_pack(
        repository: &Path,
        destination: &Path,
        name: &str,
    ) -> Result<PathBuf, RepackError> {
        run_git(
            Command::new("git")
                .arg("-C")
                .arg(repository)
                .args(["repack", "--quiet", "-a", "-d"]),
            "pack test repository",
        )?;
        let source = std::fs::read_dir(repository.join(".git/objects/pack"))
            .map_err(|error| io_error("read test pack directory", error))?
            .filter_map(std::result::Result::ok)
            .map(|entry| entry.path())
            .find(|path| {
                path.extension()
                    .is_some_and(|extension| extension == "pack")
            })
            .ok_or_else(|| {
                io_error(
                    "find test pack",
                    io::Error::new(io::ErrorKind::NotFound, "no pack generated"),
                )
            })?;
        let target = destination.join(format!("{name}.pack"));
        std::fs::copy(source, &target).map_err(|error| io_error("copy test pack", error))?;
        Ok(target)
    }

    fn source_descriptor(path: PathBuf) -> Result<RepackSource, RepackError> {
        let (hash, size) = hash_file(&path)?;
        let installed =
            tempfile::tempdir().map_err(|error| io_error("create index root", error))?;
        let canonical_id = blake3::Hash::from_bytes(hash).to_hex().to_string();
        let pack =
            install_pack_file_from_path(installed.path(), &path, &canonical_id, size, false)?;
        let locations = PackLocationIter::open(&pack.idx_path, &pack.rev_path, size)?;
        Ok(RepackSource {
            canonical_id,
            path,
            size,
            object_count: locations.object_count(),
        })
    }

    fn git_output(command: &mut Command, operation: &'static str) -> Result<String, RepackError> {
        let Output { status, stdout, .. } = command
            .output()
            .map_err(|source| io_error(format!("run {operation}"), source))?;
        if !status.success() {
            return Err(RepackError::Git { operation, status });
        }
        String::from_utf8(stdout)
            .map(|value| value.trim().to_owned())
            .map_err(|error| {
                io_error(
                    format!("decode {operation}"),
                    io::Error::new(io::ErrorKind::InvalidData, error),
                )
            })
    }
}
