#!/usr/bin/env python3
"""Check SDK delivery coverage; test discovery is not qualification evidence."""

from __future__ import annotations

import argparse
import itertools
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DIRECTORY = ROOT / "crab/docs/architecture"


def test_exists(root: Path, reference: str) -> bool:
    path, name = reference.split("::")
    source = root / path
    if not source.is_file():
        return False
    return bool(re.search(
        rf"#\[(?:tokio::)?test(?:\([^\]]*\))?\]\s*"
        rf"(?:#\[[^\]]*\]\s*)*(?:async\s+)?fn\s+{re.escape(name)}\s*\(",
        source.read_text(),
    ))


def validate(matrix: dict, root: Path = ROOT) -> None:
    if matrix.get("schema") != "crab.sdk-capabilities" or matrix.get("version") != 1:
        raise ValueError("unsupported SDK matrix schema/version")
    phase = matrix["activated_phase"]
    if type(phase) is not int or not 0 <= phase <= 8:
        raise ValueError("activated_phase must be an integer from 0 through 8")
    if matrix["backends"] != ["direct", "managed", "http"]:
        raise ValueError("backend contract changed")
    plan = (root / "crab/docs/architecture/crab-sdk.md").read_text()
    section = plan.split("## 8. SDK 1.0 compatibility matrix")[1].split("## 9.")[0]
    rows = [line.split("|")[1:-1] for line in section.splitlines()
            if line.startswith("| ")][2:]
    labels = [row[0].strip() for row in rows]
    if list(matrix["operations"].values()) != labels:
        raise ValueError("operations must cover section 8 in order without omissions")
    contracts = {
        (operation, backend): contract.strip()
        for operation, row in zip(matrix["operations"], rows, strict=True)
        for backend, contract in zip(matrix["backends"], row[1:], strict=True)
    }
    expected = set(itertools.product(matrix["operations"], matrix["backends"]))
    seen = set()
    for cell in matrix["cells"]:
        key = (cell["operation"], cell["backend"])
        if key not in expected or key in seen:
            raise ValueError(f"unknown or duplicate cell: {key}")
        seen.add(key)
        if cell["contract"] != contracts[key]:
            raise ValueError(f"{key}: contract differs from section 8")
        excluded = cell["contract"] == "Outside 1.0"
        if excluded:
            if (cell["status"], cell["phase"], cell["required_tests"]) != (
                "excluded", None, []
            ):
                raise ValueError(f"{key}: excluded cell has delivery claims")
            continue
        owner = cell["phase"]
        if type(owner) is not int or not 1 <= owner <= 6:
            raise ValueError(f"{key}: missing implementation phase")
        status = "implemented" if owner <= phase else "planned"
        if cell["status"] != status:
            raise ValueError(f"{key}: expected status {status}")
        tests = cell["required_tests"]
        if not tests or len(tests) != len(set(tests)):
            raise ValueError(f"{key}: missing or duplicate required tests")
        for reference in tests:
            match = re.fullmatch(r"(crates/[a-z0-9-]+/tests/[a-z0-9_/]+\.rs)::([a-z0-9_]+)", reference)
            if not match:
                raise ValueError(f"{key}: invalid test reference {reference}")
            if owner > phase:
                continue
            if not test_exists(root, reference):
                raise ValueError(f"{key}: unresolved test {reference}")
    if seen != expected:
        raise ValueError(f"missing cells: {sorted(expected - seen)}")
    target_section = plan.split("### Required test targets")[1].split("Live-backend tests")[0]
    targets: dict[str, list[str]] = {}
    for line in target_section.splitlines():
        if not re.match(r"\| [1-6] \|", line):
            continue
        owner, path, cases = [value.strip() for value in line.split("|")[1:4]]
        targets.setdefault(owner, []).extend(
            path.strip("`") + "::" + name for name in re.findall(r"`([^`]+)`", cases)
        )
    if matrix.get("phase_tests") != targets:
        raise ValueError("phase tests must preserve every section-10 required case")
    for owner, references in targets.items():
        if int(owner) > phase:
            continue
        for reference in references:
            if not test_exists(root, reference):
                raise ValueError(f"phase {owner}: unresolved test {reference}")


def render(matrix: dict) -> str:
    lines = ["# SDK capability delivery inventory", "",
             "Generated by `crab/scripts/verify_sdk_capabilities.py --write`.",
             "Planned means unimplemented. Implemented means test references resolve;",
             "neither status establishes passing tests or release qualification.", "",
             "| Operation | Backend | Contract | Status | Phase | Required tests |",
             "| --- | --- | --- | --- | --- | --- |"]
    for cell in matrix["cells"]:
        tests = ", ".join(f"`{test}`" for test in cell["required_tests"]) or "—"
        lines.append(f"| {matrix['operations'][cell['operation']]} | {cell['backend']} | "
                     f"{cell['contract']} | {cell['status']} | {cell['phase'] or '—'} | {tests} |")
    lines.extend(["", "## Mandatory phase tests", ""])
    for owner, references in matrix["phase_tests"].items():
        lines.extend(f"- Phase {owner}: `{reference}`" for reference in references)
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="regenerate the Markdown view")
    args = parser.parse_args()
    matrix = json.loads((DIRECTORY / "sdk-capabilities.json").read_text())
    validate(matrix)
    output = DIRECTORY / "sdk-capabilities.md"
    rendered = render(matrix)
    if args.write:
        output.write_text(rendered)
    elif not output.is_file() or output.read_text() != rendered:
        raise ValueError("SDK Markdown is stale; run with --write")
    print(f"SDK inventory valid: {len(matrix['cells'])} cells; activated phase {matrix['activated_phase']}")


if __name__ == "__main__":
    main()
