//! Property-based tests for `PersistentChunkIndex`.
//!
//! These properties exist to catch the class of bug the original
//! report described: shards that land durably in the on-disk cache getting
//! silently wiped by a concurrent `open_or_create` call. These proptests
//! cover the broader invariants that would fail under the same bug pattern.
//!
//! Properties:
//!
//! 1. **Install → read round-trip.** After installing a sequence of
//!    shards, every `(chunk_hash, xorb_ref)` pair must be queryable
//!    via `get`, and `installed_shards()` must list exactly the
//!    shard hashes that were installed.
//!
//! 2. **Install is idempotent.** Installing the same shard twice
//!    leaves the entry count and the shard count unchanged.
//!
//! 3. **Writes survive reopen.** A freshly-opened index reads the
//!    same state the previous session committed, byte-for-byte.
//!
//! 4. **No entries vanish across installs.** After installing N
//!    disjoint shards in random order, the chunk count is exactly
//!    the sum of the individual shard sizes.
//!
//! Each property runs 64 cases by default; the `.proptest-regressions`
//! file (auto-generated by proptest on failure) seeds deterministic
//! replays for minimised counter-examples.

#![allow(clippy::unwrap_used, clippy::expect_used, reason = "test assertions")]

use std::collections::{HashMap, HashSet};

use proptest::collection::{hash_map, vec};
use proptest::prelude::*;
use tempfile::TempDir;

use crab_metadata::persistent_chunk_index::PersistentChunkIndex;
use crab_xet::xorb::format::{MerkleHash, XorbRef};

fn hash_of(seed: u64) -> MerkleHash {
    MerkleHash::from([
        seed,
        seed.wrapping_mul(31),
        seed.wrapping_mul(97),
        seed ^ 0xDEAD_BEEF,
    ])
}

fn xorb_ref_of(seed: u64, idx: u32) -> XorbRef {
    XorbRef {
        xorb_hash: hash_of(seed),
        chunk_index: idx,
        uncompressed_size: 65536,
    }
}

/// Generate a shard's worth of entries: a unique shard hash, plus a
/// map of chunk_hash → xorb_ref.
fn arb_shard() -> impl Strategy<Value = (u64, HashMap<u64, u32>)> {
    (0u64..1_000_000, hash_map(0u64..10_000, 0u32..1_000, 1..20))
}

proptest! {
    #![proptest_config(ProptestConfig {
        cases: 64,
        .. ProptestConfig::default()
    })]

    /// Install-then-read round trip.
    #[test]
    fn install_then_read_round_trips(shards in vec(arb_shard(), 1..10)) {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("prop.sqlite");
        let idx = PersistentChunkIndex::open_or_create(&path).unwrap();

        // Dedup shards by hash to satisfy the index's idempotency
        // semantics without throwing away the property.
        let mut uniq: HashMap<u64, HashMap<u64, u32>> = HashMap::new();
        for (shard_seed, entries) in shards {
            uniq.entry(shard_seed).or_insert(entries);
        }

        let mut expected: HashMap<MerkleHash, XorbRef> = HashMap::new();
        for (shard_seed, entries) in &uniq {
            let shard_hash = hash_of(*shard_seed);
            let wire: Vec<(MerkleHash, XorbRef)> = entries
                .iter()
                .map(|(k, v)| (hash_of(*k), xorb_ref_of(*shard_seed, *v)))
                .collect();
            idx.install_shard(shard_hash, &wire).unwrap();
            for (k, v) in &wire {
                // Later shards may overwrite chunk_hash from an earlier
                // shard — track the last-writer-wins state.
                expected.insert(*k, *v);
            }
        }

        // All entries must round-trip.
        for (chunk, want) in &expected {
            let got = idx.get(chunk).unwrap();
            prop_assert_eq!(got, Some(*want));
        }

        // installed_shards() must list exactly the installed hashes.
        let installed: HashSet<_> = idx.installed_shards().unwrap().into_iter().collect();
        let want: HashSet<_> = uniq.keys().map(|s| hash_of(*s)).collect();
        prop_assert_eq!(installed, want);
    }

    /// Installing the same shard twice is a no-op.
    #[test]
    fn install_is_idempotent(shard_seed in 0u64..1_000_000, n_entries in 1usize..50) {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("idem.sqlite");
        let idx = PersistentChunkIndex::open_or_create(&path).unwrap();

        let shard_hash = hash_of(shard_seed);
        let entries: Vec<(MerkleHash, XorbRef)> = (0..n_entries)
            .map(|i| (hash_of(i as u64 + 100), xorb_ref_of(shard_seed, i as u32)))
            .collect();

        idx.install_shard(shard_hash, &entries).unwrap();
        let count_after_first = idx.load_all().unwrap().len();
        let shards_after_first = idx.installed_shards().unwrap().len();

        // Second install with the same shard hash must be a no-op.
        idx.install_shard(shard_hash, &entries).unwrap();
        let count_after_second = idx.load_all().unwrap().len();
        let shards_after_second = idx.installed_shards().unwrap().len();

        prop_assert_eq!(count_after_first, count_after_second);
        prop_assert_eq!(shards_after_first, shards_after_second);
    }

    /// Writes survive reopen.
    #[test]
    fn writes_survive_reopen(shards in vec(arb_shard(), 1..5)) {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("reopen.sqlite");

        // Dedup by shard hash.
        let mut uniq: HashMap<u64, HashMap<u64, u32>> = HashMap::new();
        for (s, e) in shards { uniq.entry(s).or_insert(e); }

        let mut expected: HashMap<MerkleHash, XorbRef> = HashMap::new();
        {
            let idx = PersistentChunkIndex::open_or_create(&path).unwrap();
            for (shard_seed, entries) in &uniq {
                let wire: Vec<(MerkleHash, XorbRef)> = entries
                    .iter()
                    .map(|(k, v)| (hash_of(*k), xorb_ref_of(*shard_seed, *v)))
                    .collect();
                idx.install_shard(hash_of(*shard_seed), &wire).unwrap();
                for (k, v) in &wire { expected.insert(*k, *v); }
            }
        }

        // Reopen and verify every entry is still queryable with the
        // exact same XorbRef that was written.
        let reopened = PersistentChunkIndex::open_or_create(&path).unwrap();
        for (chunk, want) in &expected {
            prop_assert_eq!(reopened.get(chunk).unwrap(), Some(*want));
        }
        prop_assert_eq!(
            reopened.installed_shards().unwrap().len(),
            uniq.len()
        );
    }

    /// No entries vanish across installs — the chunk count equals
    /// the sum of installs when shards are disjoint.
    #[test]
    fn disjoint_installs_accumulate(shard_count in 1usize..8, entries_per_shard in 1usize..20) {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("disjoint.sqlite");
        let idx = PersistentChunkIndex::open_or_create(&path).unwrap();

        for s in 0..shard_count {
            let shard_hash = hash_of(10_000 + s as u64);
            let entries: Vec<(MerkleHash, XorbRef)> = (0..entries_per_shard)
                .map(|i| {
                    let chunk_seed = s as u64 * 100_000 + i as u64;
                    (hash_of(chunk_seed), xorb_ref_of(10_000 + s as u64, i as u32))
                })
                .collect();
            idx.install_shard(shard_hash, &entries).unwrap();
        }

        prop_assert_eq!(idx.load_all().unwrap().len(), shard_count * entries_per_shard);
        prop_assert_eq!(idx.installed_shards().unwrap().len(), shard_count);
    }
}
