[package]
name = "crab-types"
version = "0.1.0"
publish = true
edition = "2024"
license = "Apache-2.0"
repository.workspace = true
rust-version.workspace = true
description = "Shared contract types for Crab crates."

[lib]
name = "crab_types"
path = "src/lib.rs"

[dependencies]
schemars = { workspace = true }
serde = { workspace = true }
