//! `crab workflow dag` — visualize the workflow DAG.
//!
//! Parses `crab.yaml` (respecting `[workflow] discover` / `--recursive`
//! per R2), builds a [`Graph`][crab_workflow::Graph], and
//! renders the topological structure in one of two formats:
//!
//! - **ASCII**: one line per stage in topological order. Each line
//!   starts with the stage name and lists incoming deps below it
//!   prefixed with `├─ dep_name`. Source stages (no producers) show
//!   `└─ (no deps)` so the reader can distinguish "no upstream" from
//!   "we forgot to print something".
//! - **Mermaid**: a `graph TD` block with one node per stage and one
//!   edge per producer → consumer relation. Output is ready to paste
//!   into any Markdown reader that renders Mermaid.
//!
//! `--json` emits a structured `workflow.dag` envelope listing every
//! stage and every inferred edge, so tools downstream of the CLI
//! (CI dashboards, static-analysis bots) can consume the DAG without
//! reparsing yaml.
//!
//! The command is pure-read — it doesn't open the journal, doesn't
//! touch the cache, doesn't acquire the scheduler lock. Safe to run
//! mid-execution of another `crab run`.

use std::collections::{BTreeMap, BTreeSet};
use std::path::Path;

use clap::{Parser, ValueEnum};
use serde::Serialize;

use crate::core::config::Config;
use crate::core::error::{CrabError, Result};
use crate::core::output::{OutputMode, emit_json};
use crate::workflow::discover::{self, DiscoverMode};
use crate::workflow::stage::StageName;
use crate::workflow::stage::{Dep, Stage};
use crab_workflow::{Graph, Workflow};

/// Structured-output schema label for `crab workflow dag`.
pub const WORKFLOW_DAG_SCHEMA: &str = "workflow.dag";

/// Clap args for `crab workflow dag`.
#[derive(Debug, Clone, Parser, Default)]
pub struct DagArgs {
    /// Output format. ASCII is optimized for a terminal; Mermaid
    /// drops into any Markdown surface that renders `graph TD`.
    #[arg(long, value_enum, default_value_t = DagFormat::Ascii)]
    pub format: DagFormat,

    /// DVC-compatible shortcut for `--format mermaid`.
    #[arg(long, default_value_t = false)]
    pub mermaid: bool,

    /// DVC-compatible shortcut for `--format dot`.
    #[arg(long, default_value_t = false)]
    pub dot: bool,

    /// Emit Mermaid wrapped in a Markdown fenced code block.
    #[arg(long, default_value_t = false)]
    pub md: bool,

    /// Show dependency/output nodes instead of stage nodes.
    #[arg(long, short = 'o', default_value_t = false)]
    pub outs: bool,

    /// With a target, show its whole connected pipeline instead of
    /// only the target and its ancestors.
    #[arg(long, default_value_t = false)]
    pub full: bool,

    /// Collapse foreach/matrix expansions into their base stage node.
    #[arg(long, default_value_t = false)]
    pub collapse_foreach_matrix: bool,

    /// Merge every `crab.yaml` under the repo root (R2). Defaults
    /// to the `[workflow] discover` config setting when unset.
    #[arg(long, default_value_t = false)]
    pub recursive: bool,

    /// Structured JSON output (single envelope).
    #[arg(long, default_value_t = false)]
    pub json: bool,

    /// Optional stage target. Defaults to all stages; without
    /// `--full`, a target renders that stage plus its ancestors.
    #[arg(value_name = "TARGET")]
    pub target: Option<String>,
}

impl DagArgs {
    /// Output mode derived from `--json`. DAG output is a single
    /// terminal envelope, never a streaming event sequence.
    pub fn output_mode(&self) -> OutputMode {
        OutputMode::from_flags(self.json, false)
    }
}

/// Rendering format selector for `--format`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, ValueEnum)]
pub enum DagFormat {
    /// Human-readable tree-shaped layout, one line per stage.
    #[default]
    Ascii,
    /// `graph TD` block ready to paste into Markdown.
    Mermaid,
    /// Graphviz DOT.
    Dot,
}

// ─── Payloads ────────────────────────────────────────────────────────

/// Top-level payload for the `workflow.dag` schema.
#[derive(Debug, Serialize, schemars::JsonSchema)]
pub struct DagPayload {
    /// Stage names in topological order. Deterministic — equal-
    /// priority nodes are drawn in lexicographic order.
    pub stages: Vec<DagStage>,
    /// Producer → consumer edges inferred by the graph builder.
    /// Sorted by (producer, consumer) for stable output.
    pub edges: Vec<DagEdge>,
}

/// A stage in the DAG payload with its resource declarations.
#[derive(Debug, Serialize, schemars::JsonSchema)]
pub struct DagStage {
    pub name: String,
    /// Whether this stage was generated by `foreach` or `matrix`
    /// expansion (its name contains `@`).
    pub expanded: bool,
    pub resources: DagResources,
    /// Human-readable description from the `desc:` field.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub desc: Option<String>,
}

/// Resource declarations for a stage in the DAG JSON output.
#[derive(Debug, Serialize, schemars::JsonSchema)]
pub struct DagResources {
    pub cpu: u32,
    pub gpu: u32,
    pub memory_bytes: u64,
}

/// One edge in the rendered DAG.
#[derive(Debug, Serialize, schemars::JsonSchema)]
pub struct DagEdge {
    pub from: String,
    pub to: String,
}

struct DagView {
    nodes: Vec<DagNode>,
    edges: Vec<DagEdge>,
}

struct DagNode {
    name: String,
    expanded: bool,
    resources: DagResources,
    desc: Option<String>,
}

// ─── Entry points ────────────────────────────────────────────────────

/// CLI entry point. Dispatched from `main.rs`.
pub fn exec(args: DagArgs) -> Result<()> {
    let cwd = std::env::current_dir().map_err(CrabError::Io)?;
    run(&args, &cwd, args.output_mode())
}

/// Testable variant accepting an explicit `repo_root` and output
/// mode. Returns without side effects beyond the emitted output.
pub fn run(args: &DagArgs, repo_root: &Path, mode: OutputMode) -> Result<()> {
    // DAG rendering is read-only but still requires the layer to be
    // enabled. The command is meaningless for a repo that hasn't
    // opted in — there's nothing to render, and surfacing a fake
    // empty graph would mask the misconfiguration.
    let config = Config::resolve_local().unwrap_or_default();
    if !config.workflow.enabled {
        return Err(CrabError::WorkflowDisabled);
    }

    let discover_mode = effective_discover_mode(args, &config);
    let discovered = discover::discover(repo_root, discover_mode)?;
    if discovered.is_empty() {
        return Err(CrabError::Configuration {
            key: "no crab.yaml found; workflow dag requires a declared workflow".into(),
            origin: "cli".into(),
        });
    }
    let workflow = discover::parse_all(repo_root, &discovered)?;
    let graph = Graph::build(&workflow.stages)?;

    let selected = selected_stages(args, &graph, &workflow)?;
    let view = if args.outs {
        build_outs_view(&graph, &workflow, &selected)
    } else {
        build_stage_view(&graph, &workflow, &selected, args.collapse_foreach_matrix)
    };
    let payload = build_payload(&view);

    match mode {
        OutputMode::Json | OutputMode::Jsonl => {
            emit_json(WORKFLOW_DAG_SCHEMA, "1.0", payload);
        }
        OutputMode::Text => match effective_format(args) {
            DagFormat::Ascii => {
                let rendered = render_ascii(&view);
                print!("{rendered}");
            }
            DagFormat::Mermaid => {
                let rendered = render_mermaid(&view);
                if args.md {
                    print!("```mermaid\n{rendered}```\n");
                } else {
                    print!("{rendered}");
                }
            }
            DagFormat::Dot => {
                let rendered = render_dot(&view);
                print!("{rendered}");
            }
        },
    }
    Ok(())
}

// ─── Helpers ─────────────────────────────────────────────────────────

/// Resolve the effective discover mode from args + config, matching
/// the logic in `cmd/status_workflow.rs` so the two read-only
/// commands stay consistent.
fn effective_discover_mode(args: &DagArgs, config: &Config) -> DiscoverMode {
    use crate::core::config::WorkflowDiscover;
    if args.recursive {
        return DiscoverMode::Recursive;
    }
    match config.workflow.discover {
        WorkflowDiscover::Root => DiscoverMode::Root,
        WorkflowDiscover::Recursive => DiscoverMode::Recursive,
    }
}

fn effective_format(args: &DagArgs) -> DagFormat {
    if args.md || args.mermaid {
        DagFormat::Mermaid
    } else if args.dot {
        DagFormat::Dot
    } else {
        args.format
    }
}

/// Construct the structured `workflow.dag` payload. Works for both
/// text and JSON paths so the two always agree on stage/edge order.
fn build_payload(view: &DagView) -> DagPayload {
    let stages = view
        .nodes
        .iter()
        .map(|n| DagStage {
            name: n.name.clone(),
            expanded: n.expanded,
            resources: DagResources {
                cpu: n.resources.cpu,
                gpu: n.resources.gpu,
                memory_bytes: n.resources.memory_bytes,
            },
            desc: n.desc.clone(),
        })
        .collect();
    DagPayload {
        stages,
        edges: clone_edges(&view.edges),
    }
}

fn selected_stages(
    args: &DagArgs,
    graph: &Graph,
    workflow: &Workflow,
) -> Result<BTreeSet<StageName>> {
    let Some(raw_target) = args.target.as_deref() else {
        return Ok(graph.stages().cloned().collect());
    };
    let target = crate::cmd::run::stage_target_name(raw_target)?;
    if !workflow.stages.contains_key(&target) {
        return Err(CrabError::Configuration {
            key: format!("stage target '{raw_target}' not found in crab.yaml"),
            origin: "cli".to_owned(),
        });
    }
    if args.full {
        Ok(connected_component(graph, &target))
    } else {
        Ok(ancestors_with_target(graph, &target))
    }
}

fn ancestors_with_target(graph: &Graph, target: &StageName) -> BTreeSet<StageName> {
    let mut selected = BTreeSet::new();
    let mut stack = vec![target.clone()];
    while let Some(stage) = stack.pop() {
        if !selected.insert(stage.clone()) {
            continue;
        }
        stack.extend(graph.producers_of(&stage));
    }
    selected
}

fn connected_component(graph: &Graph, target: &StageName) -> BTreeSet<StageName> {
    let mut selected = BTreeSet::new();
    let mut stack = vec![target.clone()];
    while let Some(stage) = stack.pop() {
        if !selected.insert(stage.clone()) {
            continue;
        }
        stack.extend(graph.producers_of(&stage));
        stack.extend(graph.consumers_of(&stage));
    }
    selected
}

fn build_stage_view(
    graph: &Graph,
    workflow: &Workflow,
    selected: &BTreeSet<StageName>,
    collapse: bool,
) -> DagView {
    let mut seen_nodes = BTreeSet::new();
    let mut nodes = Vec::new();
    for stage in graph.stages().filter(|stage| selected.contains(*stage)) {
        let name = stage_display_name(stage, collapse);
        if !seen_nodes.insert(name.clone()) {
            continue;
        }
        let source = workflow.stages.get(stage);
        nodes.push(DagNode {
            name,
            expanded: !collapse && stage.is_expanded(),
            resources: source.map_or_else(default_dag_resources, stage_resources),
            desc: source.and_then(|s| s.desc.clone()),
        });
    }

    let mut edges = Vec::new();
    for consumer in graph.stages().filter(|stage| selected.contains(*stage)) {
        let to = stage_display_name(consumer, collapse);
        for producer in graph.producers_of(consumer) {
            if !selected.contains(&producer) {
                continue;
            }
            let from = stage_display_name(&producer, collapse);
            if from != to {
                edges.push(DagEdge {
                    from,
                    to: to.clone(),
                });
            }
        }
    }
    sort_dedup_edges(&mut edges);
    DagView { nodes, edges }
}

fn stage_display_name(stage: &StageName, collapse: bool) -> String {
    if collapse {
        stage.base_name().to_owned()
    } else {
        stage.as_str().to_owned()
    }
}

fn stage_resources(stage: &Stage) -> DagResources {
    DagResources {
        cpu: stage.resources.cpu,
        gpu: stage.resources.gpu,
        memory_bytes: stage.resources.memory_bytes,
    }
}

fn default_dag_resources() -> DagResources {
    DagResources {
        cpu: 1,
        gpu: 0,
        memory_bytes: 0,
    }
}

fn build_outs_view(graph: &Graph, workflow: &Workflow, selected: &BTreeSet<StageName>) -> DagView {
    let mut nodes_by_name = BTreeMap::<String, DagNode>::new();
    let mut edges = Vec::new();

    for stage_name in graph.stages().filter(|stage| selected.contains(*stage)) {
        let Some(stage) = workflow.stages.get(stage_name) else {
            continue;
        };
        let outputs = stage_artifact_nodes(stage);
        for output in &outputs {
            insert_artifact_node(&mut nodes_by_name, output.clone());
        }
        for dep in &stage.deps {
            let from = dep_node_name(dep);
            insert_artifact_node(&mut nodes_by_name, from.clone());
            for output in &outputs {
                if from != *output {
                    edges.push(DagEdge {
                        from: from.clone(),
                        to: output.clone(),
                    });
                }
            }
        }
    }

    sort_dedup_edges(&mut edges);
    let mut nodes = Vec::new();
    let edge_names: BTreeSet<String> = edges
        .iter()
        .flat_map(|edge| [edge.from.clone(), edge.to.clone()])
        .collect();
    for (name, node) in nodes_by_name {
        if edge_names.contains(&name) || !node.name.is_empty() {
            nodes.push(node);
        }
    }
    DagView { nodes, edges }
}

fn stage_artifact_nodes(stage: &Stage) -> Vec<String> {
    let mut out = Vec::new();
    for item in stage.outs.iter().map(|out| out.path.as_path()) {
        push_unique_path(&mut out, item);
    }
    for item in &stage.metrics {
        push_unique_path(&mut out, item);
    }
    for item in &stage.plots {
        push_unique_path(&mut out, item);
    }
    out
}

fn push_unique_path(out: &mut Vec<String>, path: &Path) {
    let value = path.display().to_string();
    if !out.contains(&value) {
        out.push(value);
    }
}

fn dep_node_name(dep: &Dep) -> String {
    match dep {
        Dep::Path(path) => path.display().to_string(),
        Dep::StageOut { stage, out } => format!("{stage}:{}", out.display()),
        Dep::CrabRef { repo, path, .. } => format!("{repo}:{}", path.display()),
        Dep::GitRef { url, path, .. } => format!("{url}:{}", path.display()),
        Dep::Url { url, .. } => url.clone(),
        Dep::OciImage { reference, .. } => reference.clone(),
    }
}

fn insert_artifact_node(nodes: &mut BTreeMap<String, DagNode>, name: String) {
    nodes.entry(name.clone()).or_insert_with(|| DagNode {
        name,
        expanded: false,
        resources: default_dag_resources(),
        desc: None,
    });
}

fn clone_edges(edges: &[DagEdge]) -> Vec<DagEdge> {
    edges
        .iter()
        .map(|edge| DagEdge {
            from: edge.from.clone(),
            to: edge.to.clone(),
        })
        .collect()
}

fn sort_dedup_edges(edges: &mut Vec<DagEdge>) {
    edges.sort_by(|a, b| a.from.cmp(&b.from).then(a.to.cmp(&b.to)));
    edges.dedup_by(|a, b| a.from == b.from && a.to == b.to);
}

/// Render the DAG in ASCII — one header line per stage in topo
/// order, with incoming deps indented beneath.
///
/// Expanded stages (from `foreach` / `matrix` expansion) are
/// annotated with `[expanded]` so the user can distinguish them
/// from statically-declared stages at a glance. Stages with a
/// `desc:` field show the description after the name.
fn render_ascii(view: &DagView) -> String {
    let mut out = String::new();
    if view.nodes.is_empty() {
        out.push_str("(empty workflow)\n");
        return out;
    }
    for node in &view.nodes {
        out.push_str(&node.name);
        if node.expanded {
            out.push_str(" [expanded]");
        }
        if let Some(desc) = &node.desc {
            out.push_str(" — ");
            out.push_str(desc);
        }
        out.push('\n');
        let producers = view
            .edges
            .iter()
            .filter(|edge| edge.to == node.name)
            .map(|edge| edge.from.as_str())
            .collect::<Vec<_>>();
        if producers.is_empty() {
            out.push_str("└─ (no deps)\n");
        } else {
            for (i, producer) in producers.iter().enumerate() {
                let prefix = if i + 1 == producers.len() {
                    "└─"
                } else {
                    "├─"
                };
                out.push_str(prefix);
                out.push(' ');
                out.push_str(producer);
                out.push('\n');
            }
        }
    }
    out
}

/// Render the DAG as a Mermaid `graph TD` block.
fn render_mermaid(view: &DagView) -> String {
    let mut out = String::new();
    out.push_str("graph TD\n");
    if view.nodes.is_empty() {
        return out;
    }
    let ids = mermaid_node_ids(view);
    // Emit node declarations first so sink stages with no outgoing
    // edges still appear in the diagram.
    for node in &view.nodes {
        let Some(id) = ids.get(&node.name) else {
            continue;
        };
        out.push_str("    ");
        out.push_str(id);
        out.push_str("[\"");
        out.push_str(&escape_label(&node.name));
        out.push_str("\"]\n");
    }
    for edge in &view.edges {
        let (Some(from), Some(to)) = (ids.get(&edge.from), ids.get(&edge.to)) else {
            continue;
        };
        out.push_str("    ");
        out.push_str(from);
        out.push_str(" --> ");
        out.push_str(to);
        out.push('\n');
    }
    out
}

fn mermaid_node_ids(view: &DagView) -> BTreeMap<String, String> {
    let mut ids = BTreeMap::new();
    for name in view.nodes.iter().map(|node| node.name.clone()).chain(
        view.edges
            .iter()
            .flat_map(|edge| [edge.from.clone(), edge.to.clone()]),
    ) {
        if ids.contains_key(&name) {
            continue;
        }
        ids.insert(name, format!("node{}", ids.len() + 1));
    }
    ids
}

fn render_dot(view: &DagView) -> String {
    let mut out = String::new();
    out.push_str("digraph workflow {\n");
    for node in &view.nodes {
        out.push_str("    \"");
        out.push_str(&escape_label(&node.name));
        out.push_str("\";\n");
    }
    for edge in &view.edges {
        out.push_str("    \"");
        out.push_str(&escape_label(&edge.from));
        out.push_str("\" -> \"");
        out.push_str(&escape_label(&edge.to));
        out.push_str("\";\n");
    }
    out.push_str("}\n");
    out
}

fn escape_label(label: &str) -> String {
    label.replace('\\', "\\\\").replace('"', "\\\"")
}

// ─── Tests ───────────────────────────────────────────────────────────

#[cfg(test)]
#[allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    reason = "test assertions"
)]
mod tests {
    use super::*;
    use crate::workflow::stage::{Cmd, Dep, EnvSpec, Out, OutKind, Resources, Stage};
    use crab_workflow::{Defaults, Workflow};
    use std::collections::BTreeMap;
    use std::path::PathBuf;

    fn make_stage(name: &str, deps: Vec<Dep>, outs: Vec<Out>) -> (StageName, Stage) {
        let stage_name = StageName::parse(name).expect("valid name");
        let stage = Stage {
            name: stage_name.clone(),
            cmd: Cmd::Shell("true".into()),
            deps,
            outs,
            env: EnvSpec::Inherit,
            retry: None,
            timeout: None,
            wdir: None,
            persist: false,
            nondeterministic: false,
            hermetic: false,
            params: Vec::new(),
            metrics: Vec::new(),
            plots: Vec::new(),
            side_effects: false,
            on_cache_hit: None,
            resources: Resources::default(),
            frozen: false,
            desc: None,
            meta: None,
            condition: None,
        };
        (stage_name, stage)
    }

    fn make_workflow(stages: Vec<(StageName, Stage)>) -> Workflow {
        let mut map = BTreeMap::new();
        for (name, stage) in stages {
            map.insert(name, stage);
        }
        Workflow {
            params: Vec::new(),
            metrics: Vec::new(),
            plots: Vec::new(),
            plot_configs: Vec::new(),
            artifacts: crab_workflow::ArtifactMetadata::default(),
            defaults: Defaults::default(),
            stages: map,
            workflow_membership: BTreeMap::new(),
        }
    }

    fn file_out(path: &str) -> Out {
        Out::new(PathBuf::from(path), OutKind::File)
    }

    fn path_dep(path: &str) -> Dep {
        Dep::Path(PathBuf::from(path))
    }

    fn all_selected(graph: &Graph) -> BTreeSet<StageName> {
        graph.stages().cloned().collect()
    }

    fn stage_view(graph: &Graph, workflow: &Workflow) -> DagView {
        build_stage_view(graph, workflow, &all_selected(graph), false)
    }

    fn stage_names(set: &BTreeSet<StageName>) -> Vec<&str> {
        set.iter().map(StageName::as_str).collect()
    }

    /// Three-stage linear DAG renders each stage on its own line
    /// with a single `└─` incoming-dep row for the two non-source
    /// stages and `(no deps)` for the root.
    #[test]
    fn ascii_renders_linear_three_stage_dag() {
        let wf = make_workflow(vec![
            make_stage("a", Vec::new(), vec![file_out("a.out")]),
            make_stage("b", vec![path_dep("a.out")], vec![file_out("b.out")]),
            make_stage("c", vec![path_dep("b.out")], vec![file_out("c.out")]),
        ]);
        let graph = Graph::build(&wf.stages).unwrap();
        let view = stage_view(&graph, &wf);
        let ascii = render_ascii(&view);
        let expected = "a\n└─ (no deps)\nb\n└─ a\nc\n└─ b\n";
        assert_eq!(ascii, expected);
    }

    /// Source stages without any upstream deps render the
    /// placeholder line so the reader can tell the difference
    /// between an empty rendering and a declared-but-root stage.
    #[test]
    fn ascii_marks_source_stages_with_no_deps_placeholder() {
        let wf = make_workflow(vec![make_stage("alone", Vec::new(), Vec::new())]);
        let graph = Graph::build(&wf.stages).unwrap();
        let view = stage_view(&graph, &wf);
        let ascii = render_ascii(&view);
        assert_eq!(ascii, "alone\n└─ (no deps)\n");
    }

    /// Diamond DAG (`a → b`, `a → c`, `b → d`, `c → d`) renders in
    /// Mermaid as four nodes and four edges, with deterministic
    /// edge ordering (alphabetical on the producer side).
    #[test]
    fn mermaid_renders_diamond_dag_with_all_edges() {
        let wf = make_workflow(vec![
            make_stage("a", Vec::new(), vec![file_out("a.out")]),
            make_stage("b", vec![path_dep("a.out")], vec![file_out("b.out")]),
            make_stage("c", vec![path_dep("a.out")], vec![file_out("c.out")]),
            make_stage(
                "d",
                vec![path_dep("b.out"), path_dep("c.out")],
                vec![file_out("d.out")],
            ),
        ]);
        let graph = Graph::build(&wf.stages).unwrap();
        let view = stage_view(&graph, &wf);
        let mermaid = render_mermaid(&view);
        // Header + four node declarations + four edges.
        let expected = "graph TD\n\
            \x20\x20\x20\x20node1[\"a\"]\n\
            \x20\x20\x20\x20node2[\"b\"]\n\
            \x20\x20\x20\x20node3[\"c\"]\n\
            \x20\x20\x20\x20node4[\"d\"]\n\
            \x20\x20\x20\x20node1 --> node2\n\
            \x20\x20\x20\x20node1 --> node3\n\
            \x20\x20\x20\x20node2 --> node4\n\
            \x20\x20\x20\x20node3 --> node4\n";
        assert_eq!(mermaid, expected);
    }

    /// A stage with two producers renders both incoming edges in
    /// ASCII mode with `├─` for all but the last.
    #[test]
    fn ascii_uses_branch_glyph_for_multiple_producers() {
        let wf = make_workflow(vec![
            make_stage("a", Vec::new(), vec![file_out("a.out")]),
            make_stage("b", Vec::new(), vec![file_out("b.out")]),
            make_stage("c", vec![path_dep("a.out"), path_dep("b.out")], Vec::new()),
        ]);
        let graph = Graph::build(&wf.stages).unwrap();
        let view = stage_view(&graph, &wf);
        let ascii = render_ascii(&view);
        // `c` has two producers; `a` comes before `b` alphabetically.
        assert!(
            ascii.contains("c\n├─ a\n└─ b\n"),
            "ascii missing branch layout: {ascii}"
        );
    }

    /// The JSON payload mirrors the graph: stages in topo order,
    /// edges sorted by (from, to), both deterministic across runs.
    #[test]
    fn payload_stage_and_edge_ordering_is_deterministic() {
        let wf = make_workflow(vec![
            make_stage("a", Vec::new(), vec![file_out("a.out")]),
            make_stage("b", vec![path_dep("a.out")], vec![file_out("b.out")]),
            make_stage("c", vec![path_dep("a.out")], vec![file_out("c.out")]),
            make_stage("d", vec![path_dep("b.out"), path_dep("c.out")], Vec::new()),
        ]);
        let graph = Graph::build(&wf.stages).unwrap();
        let view = stage_view(&graph, &wf);
        let payload = build_payload(&view);
        let stage_names: Vec<&str> = payload.stages.iter().map(|s| s.name.as_str()).collect();
        assert_eq!(stage_names, vec!["a", "b", "c", "d"]);
        let edges: Vec<(&str, &str)> = payload
            .edges
            .iter()
            .map(|e| (e.from.as_str(), e.to.as_str()))
            .collect();
        assert_eq!(edges, vec![("a", "b"), ("a", "c"), ("b", "d"), ("c", "d")]);
        // All stages default to cpu=1, gpu=0, memory=0.
        for stage in &payload.stages {
            assert_eq!(stage.resources.cpu, 1);
            assert_eq!(stage.resources.gpu, 0);
            assert_eq!(stage.resources.memory_bytes, 0);
            assert!(!stage.expanded, "non-expanded stage marked expanded");
        }
    }

    /// The JSON payload marks expanded stages with `expanded: true`.
    #[test]
    fn payload_marks_expanded_stages() {
        let wf = make_workflow(vec![
            make_stage("ingest", Vec::new(), vec![file_out("raw.csv")]),
            make_stage(
                "preprocess@raw_a",
                vec![path_dep("raw.csv")],
                vec![file_out("clean_a.csv")],
            ),
        ]);
        let graph = Graph::build(&wf.stages).unwrap();
        let view = stage_view(&graph, &wf);
        let payload = build_payload(&view);
        let ingest = payload.stages.iter().find(|s| s.name == "ingest").unwrap();
        assert!(!ingest.expanded);
        let expanded = payload
            .stages
            .iter()
            .find(|s| s.name == "preprocess@raw_a")
            .unwrap();
        assert!(expanded.expanded);
    }

    /// Mermaid node IDs are internal and deterministic, so labels
    /// that would collide after punctuation escaping still render as
    /// distinct nodes.
    #[test]
    fn mermaid_ids_do_not_collide_after_label_sanitization() {
        let view = DagView {
            nodes: vec![
                DagNode {
                    name: "a-b".to_owned(),
                    expanded: false,
                    resources: default_dag_resources(),
                    desc: None,
                },
                DagNode {
                    name: "a_b".to_owned(),
                    expanded: false,
                    resources: default_dag_resources(),
                    desc: None,
                },
            ],
            edges: Vec::new(),
        };
        let ids = mermaid_node_ids(&view);
        assert_ne!(ids.get("a-b"), ids.get("a_b"));
    }

    /// An empty workflow renders `(empty workflow)` in ASCII and a
    /// bare `graph TD` header in Mermaid. Both avoid emitting an
    /// unterminated tree.
    #[test]
    fn empty_workflow_renders_cleanly_in_both_formats() {
        let wf = make_workflow(Vec::new());
        let graph = Graph::build(&wf.stages).unwrap();
        let view = stage_view(&graph, &wf);
        assert_eq!(render_ascii(&view), "(empty workflow)\n");
        assert_eq!(render_mermaid(&view), "graph TD\n");
    }

    /// Expanded stages (from foreach/matrix) appear as individual
    /// nodes in the DAG with an `[expanded]` annotation in ASCII
    /// output and proper Mermaid node IDs with `@` escaped.
    #[test]
    fn expanded_stages_appear_as_individual_nodes() {
        let wf = make_workflow(vec![
            make_stage(
                "ingest",
                Vec::new(),
                vec![file_out("raw_a.csv"), file_out("raw_b.csv")],
            ),
            make_stage(
                "preprocess@raw_a",
                vec![path_dep("raw_a.csv")],
                vec![file_out("clean_a.csv")],
            ),
            make_stage(
                "preprocess@raw_b",
                vec![path_dep("raw_b.csv")],
                vec![file_out("clean_b.csv")],
            ),
            make_stage(
                "train",
                vec![path_dep("clean_a.csv"), path_dep("clean_b.csv")],
                Vec::new(),
            ),
        ]);
        let graph = Graph::build(&wf.stages).unwrap();
        let view = stage_view(&graph, &wf);

        // ASCII: expanded stages carry the [expanded] annotation.
        let ascii = render_ascii(&view);
        assert!(
            ascii.contains("preprocess@raw_a [expanded]\n"),
            "expanded annotation missing for preprocess@raw_a:\n{ascii}"
        );
        assert!(
            ascii.contains("preprocess@raw_b [expanded]\n"),
            "expanded annotation missing for preprocess@raw_b:\n{ascii}"
        );
        // Non-expanded stages do NOT carry the annotation.
        assert!(
            ascii.contains("ingest\n"),
            "ingest should not have [expanded]:\n{ascii}"
        );
        assert!(
            ascii.contains("train\n"),
            "train should not have [expanded]:\n{ascii}"
        );

        // Mermaid: internal node IDs stay simple while labels preserve `@`.
        let mermaid = render_mermaid(&view);
        assert!(
            mermaid.contains("[\"preprocess@raw_a\"]"),
            "expanded stage label missing:\n{mermaid}"
        );
        assert!(
            mermaid.contains("[\"preprocess@raw_b\"]"),
            "expanded stage label missing:\n{mermaid}"
        );
        // Edges use the generated node IDs in topological node order.
        assert!(
            mermaid.contains("node1 --> node2"),
            "edge to expanded stage missing:\n{mermaid}"
        );
        assert!(
            mermaid.contains("node1 --> node3"),
            "edge to expanded stage missing:\n{mermaid}"
        );
        assert!(
            mermaid.contains("node2 --> node4"),
            "edge from expanded stage missing:\n{mermaid}"
        );
        assert!(
            mermaid.contains("node3 --> node4"),
            "edge from expanded stage missing:\n{mermaid}"
        );
    }

    /// A target without `--full` selects the target stage and its
    /// ancestors, matching DVC's focused DAG behavior.
    #[test]
    fn target_defaults_to_ancestors() {
        let wf = make_workflow(vec![
            make_stage("a", Vec::new(), vec![file_out("a.out")]),
            make_stage("b", vec![path_dep("a.out")], vec![file_out("b.out")]),
            make_stage("c", vec![path_dep("b.out")], vec![file_out("c.out")]),
            make_stage("d", vec![path_dep("b.out")], vec![file_out("d.out")]),
            make_stage("e", Vec::new(), vec![file_out("e.out")]),
        ]);
        let graph = Graph::build(&wf.stages).unwrap();
        let args = DagArgs {
            target: Some("c".to_owned()),
            ..DagArgs::default()
        };
        let selected = selected_stages(&args, &graph, &wf).unwrap();
        assert_eq!(stage_names(&selected), vec!["a", "b", "c"]);
    }

    /// `--full` expands a target to the whole connected pipeline,
    /// including downstream stages but not disconnected workflows.
    #[test]
    fn full_target_selects_connected_component() {
        let wf = make_workflow(vec![
            make_stage("a", Vec::new(), vec![file_out("a.out")]),
            make_stage("b", vec![path_dep("a.out")], vec![file_out("b.out")]),
            make_stage("c", vec![path_dep("b.out")], vec![file_out("c.out")]),
            make_stage("d", vec![path_dep("b.out")], vec![file_out("d.out")]),
            make_stage("e", Vec::new(), vec![file_out("e.out")]),
        ]);
        let graph = Graph::build(&wf.stages).unwrap();
        let args = DagArgs {
            full: true,
            target: Some("b".to_owned()),
            ..DagArgs::default()
        };
        let selected = selected_stages(&args, &graph, &wf).unwrap();
        assert_eq!(stage_names(&selected), vec!["a", "b", "c", "d"]);
    }

    /// Collapsing foreach/matrix expansions merges expanded nodes
    /// to their base stage name and deduplicates repeated edges.
    #[test]
    fn stage_view_collapses_expanded_names() {
        let wf = make_workflow(vec![
            make_stage(
                "ingest",
                Vec::new(),
                vec![file_out("raw_a.csv"), file_out("raw_b.csv")],
            ),
            make_stage(
                "preprocess@raw_a",
                vec![path_dep("raw_a.csv")],
                vec![file_out("clean_a.csv")],
            ),
            make_stage(
                "preprocess@raw_b",
                vec![path_dep("raw_b.csv")],
                vec![file_out("clean_b.csv")],
            ),
            make_stage(
                "train",
                vec![path_dep("clean_a.csv"), path_dep("clean_b.csv")],
                Vec::new(),
            ),
        ]);
        let graph = Graph::build(&wf.stages).unwrap();
        let view = build_stage_view(&graph, &wf, &all_selected(&graph), true);
        let names: Vec<&str> = view.nodes.iter().map(|node| node.name.as_str()).collect();
        assert_eq!(names, vec!["ingest", "preprocess", "train"]);
        let edges: Vec<(&str, &str)> = view
            .edges
            .iter()
            .map(|edge| (edge.from.as_str(), edge.to.as_str()))
            .collect();
        assert_eq!(
            edges,
            vec![("ingest", "preprocess"), ("preprocess", "train")]
        );
    }

    /// DOT rendering quotes node labels and edges so punctuation in
    /// stage names or artifact paths stays Graphviz-safe.
    #[test]
    fn dot_renders_quoted_edges() {
        let wf = make_workflow(vec![
            make_stage("a", Vec::new(), vec![file_out("a.out")]),
            make_stage("b", vec![path_dep("a.out")], vec![file_out("b.out")]),
        ]);
        let graph = Graph::build(&wf.stages).unwrap();
        let view = stage_view(&graph, &wf);
        let dot = render_dot(&view);
        assert_eq!(
            dot,
            "digraph workflow {\n    \"a\";\n    \"b\";\n    \"a\" -> \"b\";\n}\n"
        );
    }

    /// Output view replaces stage nodes with dependency, output,
    /// metric, and plot artifacts linked through each producing
    /// stage's declared dependencies.
    #[test]
    fn outs_view_links_deps_to_outputs() {
        let (train_name, mut train) = make_stage(
            "train",
            vec![path_dep("clean.csv")],
            vec![file_out("model.pkl")],
        );
        train.metrics.push(PathBuf::from("scores.json"));
        let wf = make_workflow(vec![
            make_stage(
                "clean",
                vec![path_dep("raw.csv")],
                vec![file_out("clean.csv")],
            ),
            (train_name, train),
        ]);
        let graph = Graph::build(&wf.stages).unwrap();
        let view = build_outs_view(&graph, &wf, &all_selected(&graph));
        let names: Vec<&str> = view.nodes.iter().map(|node| node.name.as_str()).collect();
        assert_eq!(
            names,
            vec!["clean.csv", "model.pkl", "raw.csv", "scores.json"]
        );
        let edges: Vec<(&str, &str)> = view
            .edges
            .iter()
            .map(|edge| (edge.from.as_str(), edge.to.as_str()))
            .collect();
        assert_eq!(
            edges,
            vec![
                ("clean.csv", "model.pkl"),
                ("clean.csv", "scores.json"),
                ("raw.csv", "clean.csv")
            ]
        );
    }
}
