config:
  storageUrl: gs://team-crab-repositories/repositories

serviceAccount:
  name: crab-http-server
  annotations:
    iam.gke.io/gcp-service-account: crab-http-server@example.iam.gserviceaccount.com
