apiVersion: v1
kind: Service
{{- if and (eq .Values.service.type "LoadBalancer") (empty .Values.service.loadBalancerSourceRanges) }}
{{- fail "service.loadBalancerSourceRanges is required for a LoadBalancer" }}
{{- end }}
{{- if and (eq .Values.service.type "LoadBalancer") (empty .Values.networkPolicy.publicIngressFrom) }}
{{- fail "networkPolicy.publicIngressFrom is required for a LoadBalancer" }}
{{- end }}
metadata:
  name: {{ include "crab-http-server.fullname" . }}
  labels:
    {{- include "crab-http-server.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "crab-http-server.selectorLabels" . | nindent 4 }}
